#ifndef _TUYA_IPC_P2P_ERROR_H_
#define _TUYA_IPC_P2P_ERROR_H_

#define ERROR_P2P_SUCCESSFUL 0
#define ERROR_P2P_NOT_INITIALIZED -1
#define ERROR_P2P_ALREADY_INITIALIZED -2
#define ERROR_P2P_TIME_OUT -3
#define ERROR_P2P_INVALID_ID -4
#define ERROR_P2P_INVALID_PARAMETER -5
#define ERROR_P2P_DEVICE_NOT_ONLINE -6
#define ERROR_P2P_FAIL_TO_RESOLVE_NAME -7
#define ERROR_P2P_INVALID_PREFIX -8
#define ERROR_P2P_ID_OUT_OF_DATE -9
#define ERROR_P2P_NO_RELAY_SERVER_AVAILABLE -10
#define ERROR_P2P_INVALID_SESSION_HANDLE -11
#define ERROR_P2P_SESSION_CLOSED_REMOTE -12
#define ERROR_P2P_SESSION_CLOSED_TIMEOUT -13
#define ERROR_P2P_SESSION_CLOSED_CALLED -14
#define ERROR_P2P_REMOTE_SITE_BUFFER_FULL -15
#define ERROR_P2P_USER_LISTEN_BREAK -16
#define ERROR_P2P_MAX_SESSION -17
#define ERROR_P2P_UDP_PORT_BIND_FAILED -18
#define ERROR_P2P_USER_CONNECT_BREAK -19
#define ERROR_P2P_SESSION_CLOSED_INSUFFICIENT_MEMORY -20
#define ERROR_P2P_INVALID_APILICENSE -21
#define ERROR_P2P_FAIL_TO_CREATE_THREAD -22

#endif //// #ifndef _TUYA_IPC_P2P_ERROR_H_
