# RT-Thread building script for component
Import('RTT_ROOT')
Import('rtconfig')

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('drv_pmic', src, depend = ['RT_USING_PMIC'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
