#
#(C) Copyright 2023-2025 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier: GPL-2.0
#
# rohm display serdes drivers configuration
#
ifndef CONFIG_SPL_BUILD
obj-$(CONFIG_SERDES_DISPLAY_CHIP_ROHM_BU18TL82)		+= rohm-bu18tl82.o
obj-$(CONFIG_SERDES_DISPLAY_CHIP_ROHM_BU18RL82)		+= rohm-bu18rl82.o
endif
