# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)
src = Glob('*.c')
CPPPATH = [cwd] + [cwd + '/include']

libpath = [cwd + '/lib']

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = DefineGroup('aupipe', src, depend = ['RT_USING_AUPIPE'], CPPPATH = CPPPATH, LIBPATH = libpath)
objs = objs + group

Return('objs')
