Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += Glob('resource/*.c')
LOCAL_CPPPATH = [cwd]

group = DefineGroup('DualTrack', src, depend = ['ENABLE_DUAL_TRACKING'], LOCAL_CPPPATH = LOCAL_CPPPATH)

Return('group')
