#!/bin/sh
[ -f /etc/profile.d/RkEnv.sh ] && source /etc/profile.d/RkEnv.sh
case $1 in
start)
	if [ -f /usr/bin/t_s ]; then
		/usr/bin/t_s &
	elif [ -f /usr/bin/86UI_demo ]; then
		/usr/bin/86UI_demo &
	fi
	;;
*)
	exit 1
	;;
esac
