include ../config.mk

all:
	$(CC) -o $(TARGET) airkiss.c ../$(LIB_DIR)/$(LIB_NAME) airkiss/airkiss-lib/mipsel/libairkiss_aes.a -I../$(LIB_DIR)/
	$(CC) -static -o $(TARGET)-static airkiss.c ../$(LIB_DIR)/$(LIB_NAME) airkiss/airkiss-lib/mipsel/libairkiss_aes.a -I../$(LIB_DIR)/
clean:
	$(RM) -f *.o $(TARGET) $(TARGET)-static
