Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src  = Glob('*.c')
src += Glob('resource/*.c')
LOCAL_CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = ['RT_USING_IOT_DISPLAY'], LOCAL_CPPPATH = LOCAL_CPPPATH)

Return('group')
