# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2020 Rockchip Electronics Co., Ltd.

PROJECT		:= RK3568
SOC		:= RK3568
CPU		:= -march=rv32imac -mabi=ilp32

-include ../../../middleware/benchmark/benchmark.mk
include ../../common/GCC/riscv.mk
