Import('RTT_ROOT')
Import('rtconfig')
from building import *

src	= Split('''
	main/bt_app_av.c
	main/bt_app_core.c
	main/main.c
''')

CPPPATH = ""

group = DefineGroup('examples', src, depend = ['A2DP_SINK_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
