# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)
src = Glob('*.c')
CPPPATH = [cwd]

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = DefineGroup('HTTP', src, depend = ['RT_USING_NET_HTTP'], CPPPATH = CPPPATH)
objs = objs + group

Return('objs')
