set(RELOCATED_HOST_DIR $ENV{AIQ_BUILD_HOST_DIR})
set(TOOLCHAIN_TRIPLE $ENV{AIQ_BUILD_TOOLCHAIN_TRIPLE})
set(TOOLCHAIN_SYSROOT $ENV{AIQ_BUILD_SYSROOT})
set(TOOLCHAIN_ARCH $ENV{AIQ_BUILD_ARCH})

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

set(CMAKE_SYSTEM_NAME Linux)
if (TOOLCHAIN_ARCH STREQUAL "arm")
set(CMAKE_SYSTEM_PROCESSOR armv7l)
elseif(TOOLCHAIN_ARCH STREQUAL "aarch64")
set(CMAKE_SYSTEM_PROCESSOR aarch64)
endif()

set(CMAKE_SKIP_RPATH TRUE)

set(CMAKE_C_FLAGS_DEBUG "" CACHE STRING "Debug CFLAGS")
set(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "Debug CXXFLAGS")
set(CMAKE_C_FLAGS_RELEASE " -DNDEBUG" CACHE STRING "Release CFLAGS")
set(CMAKE_CXX_FLAGS_RELEASE " -DNDEBUG" CACHE STRING "Release CXXFLAGS")

set(CMAKE_C_FLAGS "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CACHE STRING "Default CFLAGS")
set(CMAKE_CXX_FLAGS "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CACHE STRING "Default CXXFLAGS")
set(CMAKE_EXE_LINKER_FLAGS "" CACHE STRING "Default LDFLAGS for executables")

set(CMAKE_INSTALL_SO_NO_EXE 0)

set(CMAKE_PROGRAM_PATH "${RELOCATED_HOST_DIR}/bin")
set(CMAKE_SYSROOT "${RELOCATED_HOST_DIR}/${TOOLCHAIN_TRIPLE}/${TOOLCHAIN_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${RELOCATED_HOST_DIR}/${TOOLCHAIN_TRIPLE}/${TOOLCHAIN_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${RELOCATED_HOST_DIR}/${TOOLCHAIN_TRIPLE}/${TOOLCHAIN_SYSROOT}")

set(TOOLCHAIN_PREFIX ${TOOLCHAIN_TRIPLE}-)

set(CMAKE_C_FLAGS_INIT " -B${RELOCATED_HOST_DIR}/${TOOLCHAIN_TRIPLE}/bin")
set(CMAKE_CXX_FLAGS_INIT " -B${RELOCATED_HOST_DIR}/${TOOLCHAIN_TRIPLE}/bin/ ")

set(gcc_toolchain "${RELOCATED_HOST_DIR}")
set(triple ${TOOLCHAIN_TRIPLE})
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_ASM_COMPILER_TARGET ${triple})
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN ${gcc_toolchain})
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN ${gcc_toolchain})
set(CMAKE_CXX_COMPILER_TARGET ${triple})

set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld" CACHE INTERNAL "library linker flags")
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld" CACHE INTERNAL "exectuable linker flags")
set(CMAKE_OBJCOPY "llvm-objcopy" CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL "llvm-size" CACHE INTERNAL "size tool")
set(CMAKE_NM "llvm-nm" CACHE INTERNAL "nm tool")
set(CMAKE_RANLIB "llvm-ranlib" CACHE INTERNAL "ranlib tool")
set(CMAKE_AR "llvm-ar" CACHE INTERNAL "ar tool")
