Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('memtester', src, depend = ['RT_USING_COMMON_MEMTESTER'], CPPPATH = CPPPATH)

Return('group')
