# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

src = Glob('*.c') + Glob('example/*.c') + Glob('cjson/*.c') + Glob('core/*.c') + Glob('basics/*.c')
CPPPATH = [cwd] + [cwd + '/cjson'] + [cwd + '/core']

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = DefineGroup('aupipe', src, depend = ['RT_USING_AUPIPE'], CPPPATH = CPPPATH)
objs = objs + group

Return('objs')
