#!/bin/sh

load_luckfoxconfig() {
	if [ -f /usr/bin/luckfox-config ]; then
		luckfox-config load
		luckfox_switch_rgb_resolution &
	fi
}

case $1 in
start)
	load_luckfoxconfig
	;;
*)
	exit 1
	;;
esac
