#!/bin/sh
[ -f /etc/profile.d/RkEnv.sh ] && source /etc/profile.d/RkEnv.sh
case $1 in
        start)
                if command -v amixer >/dev/null 2>&1; then
                        amixer set 'ADC ALC Left' 26 > /dev/null 2>&1
                        amixer set 'ADC ALC Right' 26 > /dev/null 2>&1
                        amixer set 'ADC MIC Left Gain' 3 > /dev/null 2>&1
                        amixer set 'ADC MIC Right Gain' 3 > /dev/null 2>&1
                        amixer set 'ADC MICBIAS Voltage' 'VREFx0_975' > /dev/null 2>&1
                        amixer set 'ADC Mode' 'SingadcL' > /dev/null 2>&1
                fi
                ;;
        *)
                exit 1
                ;;
esac
