include ../config.mk

all:
	$(CC) -o $(TARGET) smarticomm.c ../$(LIB_DIR)/$(LIB_NAME) -I../$(LIB_DIR)/
	$(CC) -static -o $(TARGET) smarticomm.c ../$(LIB_DIR)/$(LIB_NAME) -I../$(LIB_DIR)/	
clean:
	$(RM) -f *.o $(TARGET) $(TARGET)-static
