all:
	$(MAKE) -C lib_ssv_smartlink -f Makefile.lib
#	$(MAKE) -C airkiss -f Makefile.airkiss
#	$(MAKE) -C qqlink -f Makefile.qqlink
#	$(MAKE) -C smarticomm -f Makefile.smarticomm
	$(MAKE) -C user_smartlink -f Makefile.user_smartlink

clean:
	$(MAKE) -C lib_ssv_smartlink -f Makefile.lib     clean
#	$(MAKE) -C airkiss -f Makefile.airkiss clean
#	$(MAKE) -C qqlink -f Makefile.qqlink  clean
#	$(MAKE) -C smarticomm -f Makefile.smarticomm clean
	$(MAKE) -C user_smartlink -f Makefile.user_smartlink clean
	
