#
# (C) Copyright 2022 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

ifneq ($(CONFIG_TPL_BUILD)$(CONFIG_TPL_TINY_FRAMEWORK),yy)
ifneq ($(CONFIG_SPL_BUILD)$(CONFIG_SPL_DECOMP_HEADER),yy)
obj-y += syscon_rv1106.o
endif
endif
obj-y += clk_rv1106.o
obj-y += rv1106.o
