/*
 * Copyright (c) 2015 iComm-semi Ltd.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _LINUX_80211_H_
#define _LINUX_80211_H_

#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,7,0)
#define INDEX_80211_BAND_2GHZ NL80211_BAND_2GHZ
#define INDEX_80211_BAND_5GHZ NL80211_BAND_5GHZ
#define INDEX_80211_BAND_60GHZ NL80211_BAND_60GHZ
#else
#define INDEX_80211_BAND_2GHZ IEEE80211_BAND_2GHZ
#define INDEX_80211_BAND_5GHZ IEEE80211_BAND_5GHZ
#define INDEX_80211_BAND_60GHZ IEEE80211_BAND_60GHZ
#endif            

#endif /* _LINUX_80211_H_ */
