# Import('RTT_ROOT')
# Import('rtconfig')
from building import *

src  = Glob('*.c')
cwd  = GetCurrentDir()
LOCAL_CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = ['RT_USING_ROCKCHIP_DEMO'], LOCAL_CPPPATH = LOCAL_CPPPATH)

Return('group')
