#
# (C) Copyright 2017 Rockchip Electronics Co., Ltd.
#
# SPDX-License-Identifier:     GPL-2.0+
#


obj-y += clk_px30.o
ifneq ($(CONFIG_TPL_BUILD)$(CONFIG_TPL_TINY_FRAMEWORK),yy)
obj-y += syscon_px30.o
endif
obj-y += px30.o
