/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2020 Rockchip Electronics Co., Ltd.
 */

#ifndef _HAL_CONF_H_
#define _HAL_CONF_H_

/* HAL SOC Config */
#define RKMCU_RK2206
#define SYS_TIMER TIMER5 /* System timer designation (RK TIMER) */

/* HAL Driver Config */
#define HAL_ACDCDIG_MODULE_ENABLED
#define HAL_AUDIOPWM_MODULE_ENABLED
#define HAL_CRU_MODULE_ENABLED
#define HAL_CRYPTO_MODULE_ENABLED
#define HAL_DCACHE_MODULE_ENABLED
#define HAL_DSP_MODULE_ENABLED
#define HAL_DWDMA_MODULE_ENABLED
#define HAL_EFUSE_MODULE_ENABLED
#define HAL_FSPI_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_HCD_MODULE_ENABLED
#define HAL_HWSPINLOCK_MODULE_ENABLED
#define HAL_HYPERPSRAM_MODULE_ENABLED
#define HAL_I2C_MODULE_ENABLED
#define HAL_I2STDM_MODULE_ENABLED
#define HAL_ICACHE_MODULE_ENABLED
#define HAL_MBOX_MODULE_ENABLED
#define HAL_NVIC_MODULE_ENABLED
#define HAL_PCD_MODULE_ENABLED
#define HAL_PDM_MODULE_ENABLED
#define HAL_PINCTRL_MODULE_ENABLED
#define HAL_PM_CPU_SLEEP_MODULE_ENABLED
#define HAL_PM_RUNTIME_MODULE_ENABLED
#define HAL_PM_SLEEP_MODULE_ENABLED
#define HAL_QPIPSRAM_MODULE_ENABLED
#define HAL_PVTM_MODULE_ENABLED
#define HAL_PWM_MODULE_ENABLED
#define HAL_PWR_INTBUS_MODULE_ENABLED
#define HAL_PWR_MODULE_ENABLED
#define HAL_SARADC_MODULE_ENABLED
#define HAL_SDIO_MODULE_ENABLED
#define HAL_SNOR_MODULE_ENABLED
#define HAL_SPI2APB_MODULE_ENABLED
#define HAL_SPI_MODULE_ENABLED
#define HAL_SYSTICK_MODULE_ENABLED
#define HAL_TIMER_MODULE_ENABLED
#define HAL_TOUCHKEY_MODULE_ENABLED
#define HAL_TSADC_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED
#define HAL_VAD_MODULE_ENABLED
#define HAL_VICAP_MODULE_ENABLED
#define HAL_VOP_MODULE_ENABLED
#define HAL_WDT_MODULE_ENABLED

/* HAL_DBG SUB CONFIG */
#define HAL_SYSLOG printf
#define HAL_DBG_ON
#define HAL_DBG_INFO_ON
#define HAL_DBG_WRN_ON
#define HAL_DBG_ERR_ON
#define HAL_ASSERT_ON

#ifdef HAL_SNOR_MODULE_ENABLED
#define HAL_SNOR_FSPI_HOST
#define HAL_FSPI_XIP_ENABLE
#endif

#ifdef HAL_HWSPINLOCK_MODULE_ENABLED
#define HAL_HWSPINLOCK_OWNER_ID 1
#endif

#endif
