Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#')), 'include/iq_parser_v2/', 'include/common']
LIBS    = ['libfastae_gcc.a','libfastawb_gcc.a']
LIBPATH = [GetCurrentDir()]
CPPDEFINES = ['ISP_HW_V32']

group = DefineGroup('battery-ipc', src, depend = ['RT_USING_RK_BATTERY_IPC'], CPPPATH = CPPPATH, LIBS = LIBS, LIBPATH = LIBPATH, CPPDEFINES = CPPDEFINES)

Return('group')
