#
# (C) Copyright 2020 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

ifneq ($(CONFIG_TPL_BUILD)$(CONFIG_TPL_TINY_FRAMEWORK),yy)
obj-y += syscon_rk3528.o
endif
obj-y += rk3528.o
obj-y += clk_rk3528.o
