#!/bin/bash
SSV_DRV_PATH=$PWD
KERNEL_OBJ_PATH=/lib/modules/`uname -r`/build
INSTALL_PATH=kernel/drivers/net/wireless/ssv6200
PLATFORM_TOOLCHAIN=
PLATFORM_ARCH=x86

make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH ARCH=$PLATFORM_ARCH CROSS_COMPILE=$PLATFORM_TOOLCHAIN clean
make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH ARCH=$PLATFORM_ARCH CROSS_COMPILE=$PLATFORM_TOOLCHAIN modules
make -C $SSV_DRV_PATH SSV_DRV_PATH=$SSV_DRV_PATH CROSS_COMPILE=$PLATFORM_TOOLCHAIN strip
make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH INSTALL_PATH=$INSTALL_PATH install
