Import('RTT_ROOT')
Import('rtconfig')

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

# Remove some warnings for pcm plugins.
LOCAL_CCFLAGS = ' -Wno-enum-compare'

group = DefineGroup('Audio_PCM_Plugins',
                    src,
                    depend = ['RT_USING_DRIVER_AUDIO_PCM_PLUGIN'],
                    CPPPATH = CPPPATH,
                    LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')