#
# (C) Copyright 2015 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += rk3036.o clk_rk3036.o

ifndef CONFIG_TPL_BUILD
obj-y += syscon_rk3036.o
endif

obj-y += sdram_rk3036.o
