/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2020 Rockchip Electronics Co., Ltd.
 */

#ifndef _MODULEINFO_H
#define _MODULEINFO_H

#undef EXT
#ifdef _IN_MODULEINFO_
#define EXT
#else
#define EXT extern
#endif

typedef enum
{
    SEGMENT_ID_SYS,
    SEGMENT_ID_INIT,
    SEGMENT_ID_PMU,
    SEGMENT_ID_RESUME,
    SEGMENT_ID_MUSIC_PLAY_MENU_TASK,
    SEGMENT_ID_MUSIC_PLAY_MENU_INIT,
    SEGMENT_ID_USBSERVER_TASK,
    SEGMENT_ID_USBSERVER_INIT,
    SEGMENT_ID_MAIN_TASK,
    SEGMENT_ID_MAIN_INIT,
    SEGMENT_ID_RECORD_SHELL,
    SEGMENT_ID_MUSIC_SHELL,
    SEGMENT_ID_EFFECT_MODULE,
    SEGMENT_ID_TIMER_DEV,
    SEGMENT_ID_TIMER_INIT,
    SEGMENT_ID_TIMER_SHELL,
    SEGMENT_ID_ADC_DEV,
    SEGMENT_ID_ADC_INIT,
    SEGMENT_ID_ADC_SHELL,
    SEGMENT_ID_KEY_DEV,
    SEGMENT_ID_KEY_INIT,
    SEGMENT_ID_KEY_SHELL,
    SEGMENT_ID_PWM_DEV,
    SEGMENT_ID_PWM_INIT,
    SEGMENT_ID_PWM_SHELL,
    SEGMENT_ID_BCORE_DEV,
    SEGMENT_ID_BCORE_INIT,
    SEGMENT_ID_BCORE_SHELL,
    SEGMENT_ID_MSG_DEV,
    SEGMENT_ID_MSG_INIT,
    SEGMENT_ID_MSG_SHELL,
    SEGMENT_ID_DIR_DEV,
    SEGMENT_ID_DIR_INIT,
    SEGMENT_ID_DIR_SHELL,
    SEGMENT_ID_FILESTREAM_TASK,
    SEGMENT_ID_FILESTREAM_INIT,
    SEGMENT_ID_HTTP_TASK,
    SEGMENT_ID_HTTP_INIT,
    SEGMENT_ID_MEDIA_TASK,
    SEGMENT_ID_MEDIA_INIT,
    SEGMENT_ID_STREAMCONTROL_TASK,
    SEGMENT_ID_STREAMCONTROL_INIT,
    SEGMENT_ID_AUDIOCONTROL_TASK,
    SEGMENT_ID_AUDIOCONTROL_INIT,
    SEGMENT_ID_RECORDCONTROL_TASK,
    SEGMENT_ID_RECORDCONTROL_INIT,
    SEGMENT_ID_WAV_ENCODE,
    SEGMENT_ID_AMR_ENCODE,
    SEGMENT_ID_MP3_ENCODE,
    SEGMENT_ID_MP3_DECODE,
    SEGMENT_ID_WAV_DECODE,
    SEGMENT_ID_AMR_DECODE,
    SEGMENT_ID_AAC_DECODE,
    SEGMENT_ID_I2S_DEV,
    SEGMENT_ID_I2S_INIT,
    SEGMENT_ID_I2S_SHELL,
    SEGMENT_ID_ROCKCODEC_DEV,
    SEGMENT_ID_ROCKCODEC_INIT,
    SEGMENT_ID_ROCKCODEC_SHELL,
    SEGMENT_ID_AUDIO_DEV,
    SEGMENT_ID_AUDIO_INIT,
    SEGMENT_ID_AUDIO_SHELL,
    SEGMENT_ID_USBAUDIO_DEV,
    SEGMENT_ID_USBAUDIO_INIT,
    SEGMENT_ID_USBAUDIO_SHELL,
    SEGMENT_ID_USBMSC_DEV,
    SEGMENT_ID_USBMSC_HOST,
    SEGMENT_ID_USBMSC_INIT,
    SEGMENT_ID_USBMSC_SHELL,
    SEGMENT_ID_MAILBOX_DEV,
    SEGMENT_ID_MAILBOX_INIT,
    SEGMENT_ID_MAILBOX_SHELL,
    SEGMENT_ID_FIFO_DEV,
    SEGMENT_ID_FIFO_INIT,
    SEGMENT_ID_FIFO_SHELL,
    SEGMENT_ID_SD_DEV,
    SEGMENT_ID_SD_INIT,
    SEGMENT_ID_SD_SHELL,
    SEGMENT_ID_I2C_DEV,
    SEGMENT_ID_I2C_INIT,
    SEGMENT_ID_I2C_SHELL,
    SEGMENT_ID_USBOTG_DEV,
    SEGMENT_ID_USBOTG_HOST,
    SEGMENT_ID_USBOTG_INIT,
    SEGMENT_ID_USBOTG_SHELL,
    SEGMENT_ID_SDC_DEV,
    SEGMENT_ID_SDC_INIT,
    SEGMENT_ID_SDC_SHELL,
    SEGMENT_ID_DMA_SHELL,
    SEGMENT_ID_EMMC_DEV,
    SEGMENT_ID_EMMC_INIT,
    SEGMENT_ID_EMMC_SHELL,
    SEGMENT_ID_LUN_INIT,
    SEGMENT_ID_LUN_SHELL,
    SEGMENT_ID_PAR_DEV,
    SEGMENT_ID_PAR_INIT,
    SEGMENT_ID_PAR_SHELL,
    SEGMENT_ID_FAT_DEV,
    SEGMENT_ID_FAT_INIT,
    SEGMENT_ID_FAT_SHELL,
    SEGMENT_ID_FILE_DEV,
    SEGMENT_ID_FILE_INIT,
    SEGMENT_ID_FILE_SHELL,
    SEGMENT_ID_SDIO_DEV,
    SEGMENT_ID_SDIO_INIT,
    SEGMENT_ID_SDIO_SHELL,
    SEGMENT_ID_UART_DEV,
    SEGMENT_ID_UART_INIT,
    SEGMENT_ID_UART_SHELL,
    SEGMENT_ID_WDOG_DEV,
    SEGMENT_ID_WDOG_INIT,
    SEGMENT_ID_WDOG_SHELL,
    SEGMENT_ID_WIFI_APPTASK_INIT,
    SEGMENT_ID_WIFI_APPTASK,
    SEGMENT_ID_AP6181_INIT,
    SEGMENT_ID_AP6181_ESAY_SETUP,
    SEGMENT_ID_AP6181_WIFI,
    SEGMENT_ID_AP6181_SHELL,
    SEGMENT_ID_WIFIMSG_SHELL,
    SEGMENT_ID_LWIP,
    SEGMENT_ID_LWIP_API,
    SEGMENT_ID_PING_SHELL,
    SEGMENT_ID_IPCONFIG_SHELL,
    SEGMENT_ID_HTTP,
    SEGMENT_ID_HTTPD,
    SEGMENT_ID_MBEDTLS,
    SEGMENT_ID_SPIFLASH_INIT,
    SEGMENT_ID_SPIFLASH_DEV,
    SEGMENT_ID_SPIFLASH_SHELL,
    SEGMENT_ID_SPI_INIT,
    SEGMENT_ID_SPI_DEV,
    SEGMENT_ID_SPI_SHELL,
    SEGMENT_ID_WIFI_FIRMAVE_ONE,
    SEGMENT_ID_WIFI_FIRMAVE_MFG,
    SEGMENT_ID_WIFI_FIRMAVE_TWO,
    SEGMENT_ID_AUDIO_EQ_DATA,
    SEGMENT_ID_SYS_CMD,
    SEGMENT_ID_DEV_CMD,
    SEGMENT_ID_TASK_CMD,
    SEGMENT_ID_CUSTOM_CMD,
    SEGMENT_ID_BB_CODE,
    SEGMENT_ID_MP3_DECODE_BIN,
    SEGMENT_ID_WAV_DECODE_BIN,
    SEGMENT_ID_AMR_DECODE_BIN,
    SEGMENT_ID_AAC_DECODE_BIN,
    SEGMENT_ID_WAV_ENCODE_BIN,
    SEGMENT_ID_AMR_ENCODE_BIN,
    SEGMENT_ID_MP3_ENCODE_BIN,
    SEGMENT_ID_FADE_MODULE,
    SEGMENT_ID_SHELL_CMD_NAME,
    SEGMENT_ID_TASK_INF,
    SEGMENT_ID_FW_SHELL,
    SEGMENT_ID_GPIO_SHELL,
    SEGMENT_ID_STACK1,
    SEGMENT_ID_STACK2,
    SEGMENT_ID_STACK3,
    SEGMENT_ID_SRC_FILTER,
    MAX_SEGMENT_NUM

} SEGMENT_ID;

typedef struct _SEGMENT_INFO_T
{
    uint32_t *CodeLoadBase;
    uint32_t *CodeImageBase;
    uint32_t *CodeImageLength;

    uint32_t *DataLoadBase;
    uint32_t *DataImageBase;
    uint32_t *DataImageLength;

    uint32_t *BssImageBase;
    uint32_t *BssImageLength;
    uint8_t Name[16];
} SEGMENT_INFO_T;

typedef struct _SEGMENT_INFO_TABLE
{
    uint32_t SegmentNum;
    SEGMENT_INFO_T Segment[MAX_SEGMENT_NUM];

} SEGMENT_INFO_TABLE;

typedef struct _SYSTEM_DEFAULT_PARA_T
{
    uint32_t SDEnable;
    uint32_t FMEnable;

    uint32_t gLanguage;
    uint32_t Volume;
    uint32_t Volume1;
    uint32_t Volume2;

    uint32_t BLMode;
    uint32_t BLevel;
    uint32_t BLtime;

    uint32_t SettingPowerOffTime;
    uint32_t IdlePowerOffTime;

    uint32_t AvlsEnabled;
    uint32_t BeepEnabled;
    uint32_t FactoryVolLimit;

    uint32_t MusicRepMode;
    uint32_t MusicPlayOrder;
    uint32_t MusicBassBoost;
    uint32_t MusicEqSel;
    uint32_t MusicPlayFxSel;

    uint32_t FMArea;
    uint32_t FMStereo;
    uint32_t FMScanSensitivity;

    uint32_t PicAutoPlayTime;

    uint32_t TextAutoPlayTime;

    uint32_t ImageIndex;

    uint32_t LanguagesEnableTbl[64];

} SYSTEM_DEFAULT_PARA_T;

typedef struct _FIRMWARE_INFO_T
{
    uint32_t *LoadStartBase;
    SEGMENT_INFO_TABLE SegmentInfo;
    SYSTEM_DEFAULT_PARA_T SysDefaultPara;

} FIRMWARE_INFO_T;

void SysBSSInit(void);

#endif
