# Rockchip sample Makefile

all:
	@$(SAMPLE_CC) $(SAMPLE_CFLAGS) sample_vi_vpss_osd_venc.c -o sample_vi_vpss_osd_venc $(LD_FLAGS)

install:
	@mv -f sample_vi_vpss_osd_venc $(SAMPLE_OUT_DIR)/bin

clean:
	@echo "clean venc"
