#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "des_core.h"

static void rk_crypto_ofb128_encrypt(void *ctx, const unsigned char *in, unsigned char *out,
			int len, unsigned char *ivec, unsigned int *num,block128_f block)
{
	int n, l=0;

	n = *num;

	while (l<len) {
		if (n==0) {
			(*block)(ivec, ivec, ctx);
		}
		out[l] = in[l] ^ ivec[n];
		++l;
		n = (n+1) % DES_BLOCK_SIZE;
	}

	*num=n;
}

/* XTS makes use of two different keys, usually generated by splitting
 * the supplied block cipher's key in half.
 * Because of the splitting, users wanting AES 256 and AES 128 encryption
 * will need to choose key sizes of 512 bits and 256 bits respectively.
 */
int rk_des_ofb_encrypt(const unsigned char *in, unsigned char *out,
        unsigned long length, const unsigned char *key, const int key_len,
        unsigned char *ivec, const int enc)
{
	rk_des_context  ctx;
	rk_des3_context ctx3;
	unsigned int num = 0;

	if(key_len != 8 && key_len != 16 && key_len != 24)
		return -1;

	if(length == 0)
		return -1;

	switch(key_len){
	case 8:
		rk_des_setkey_enc(&ctx, key);
		rk_crypto_ofb128_encrypt((void*)&ctx, in, out, length, ivec, &num, rk_des_crypt_ecb);
		break;
	case 16:
		rk_des3_set2key_enc(&ctx3, key);
		rk_crypto_ofb128_encrypt((void*)&ctx3, in, out, length, ivec, &num, rk_des3_crypt_ecb);
		break;
	case 24:
		rk_des3_set3key_enc(&ctx3, key);
		rk_crypto_ofb128_encrypt((void*)&ctx3, in, out, length, ivec, &num, rk_des3_crypt_ecb);
		break;
	default:
		return -1;
	}

	return 0;
}

