#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sm4_core.h"

static void rk_crypto_ofb128_encrypt(void *ctx, const unsigned char *in, unsigned char *out,
			int len, unsigned char *ivec, unsigned int *num,block128_f block)
{
	int n, l=0;

	n = *num;

	while (l<len) {
		if (n==0) {
			(*block)(ivec, ivec, ctx);
		}
		out[l] = in[l] ^ ivec[n];
		++l;
		n = (n+1) % SM4_BLOCK_SIZE;
	}

	*num=n;
}

/* XTS makes use of two different keys, usually generated by splitting
 * the supplied block cipher's key in half.
 * Because of the splitting, users wanting AES 256 and AES 128 encryption
 * will need to choose key sizes of 512 bits and 256 bits respectively.
 */
int rk_sm4_ofb_encrypt(const unsigned char *in, unsigned char *out,
        unsigned long length, const unsigned char *key, const int key_len,
        unsigned char *ivec, const int enc)
{
	sm4_context  ctx;
	unsigned int num = 0;

	if(key_len != 16)
		return -1;

	if(length == 0)
		return -1;

	rk_sm4_setkey_enc(&ctx, key);
	rk_crypto_ofb128_encrypt((void*)&ctx, in, out, length, ivec, &num, rk_rk_sm4_crypt_ecb);
	return 0;
}


