#
#(C) Copyright 2023-2025 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier: GPL-2.0
#
# novo display serdes drivers configuration
#
ifndef CONFIG_SPL_BUILD
obj-$(CONFIG_SERDES_DISPLAY_CHIP_NOVO)		+= novo-nca9539.o
endif
