Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('CodecDrivers', src, depend = ['RT_USING_CODEC'], CPPPATH = CPPPATH)

Return('group')
