# Import('RTT_ROOT')
# Import('rtconfig')
from building import *

src  = Glob('*.c')
cwd  = GetCurrentDir()
CPPPATH = [cwd]
objs = []
list = os.listdir(cwd)
libs = []
libs = ['libimage_gcc']
libpath = [cwd]

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
       objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = DefineGroup('imagecom', src, depend = ['RT_USING_DISPLAY'], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)
objs = objs + group

Return('objs')
