# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2020 Rockchip Electronics Co., Ltd.

PROJECT		:= RV1106
SOC		:= RV1106
CPU		:= -march=rv32imac -mabi=ilp32

include ../../common/GCC/riscv.mk
