Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src  = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = ['RT_USING_DLMODULE_APP_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
