obj-y += rockit-ko.o
rockit-ko-objs += ./mpi/mpi.o
rockit-ko-objs += ./mpi/mpi_log.o
rockit-ko-objs += ./mpi/mpi_list.o
rockit-ko-objs += ./mpi/mpi_ioctl.o
rockit-ko-objs += ./mpi/mpi_queue.o
rockit-ko-objs += ./mpi/mpi_job.o
rockit-ko-objs += ./mpi/mpi_dev.o
rockit-ko-objs += ./mpi/mpi_sysfs.o
rockit-ko-objs += ./mpi/mpi_buf.o
rockit-ko-objs += ./mcu/mcu.o
rockit-ko-objs += ./isp/rockit_isp.o
rockit-ko-objs += ./common/argparse.o
rockit-ko-objs += ./rockit_init.o
rockit-ko-objs += ./vpss/vpss.o
rockit-ko-objs += ./avs/avs.o
rockit-ko-objs += ./rga/vrga.o
rockit-ko-objs += ./rga/rga_utils.o
rockit-ko-objs += ./sys/vsys.o
rockit-ko-objs += ./venc/venc.o
rockit-ko-objs += ./aiisp/aiisp.o
rockit-ko-objs += ./vrgn/vrgn.o
rockit-ko-objs += ./vicap/rockit_cif.o
rockit-ko-objs += ./valloc/valloc.o
rockit-ko-objs += ./vi/vvi.o
ifneq ($(CONFIG_ROCKCHIP_THUNDER_BOOT_SERVICE),y)
rockit-ko-objs += ../fakecode.o
endif
