#
# (C) Copyright Fuzhou Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-$(CONFIG_ROCKCHIP_EBC_TCON) += rk_ebc_tcon.o
obj-$(CONFIG_ROCKCHIP_TPS65185) += tps65185.o
obj-$(CONFIG_ROCKCHIP_EINK_DISPLAY) += rk_eink_display.o epdlut/
