#
#(C) Copyright 2023-2025 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier: GPL-2.0
#
# rockchip display serdes drivers configuration
#
ifndef CONFIG_SPL_BUILD
obj-$(CONFIG_SERDES_DISPLAY_CHIP_ROCKCHIP_RKX111)	+= rockchip-rkx111.o
obj-$(CONFIG_SERDES_DISPLAY_CHIP_ROCKCHIP_RKX121)	+= rockchip-rkx121.o
endif
