Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src  = Glob('*.c')
src += Glob('resource/*.c')
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = ['RT_USING_ANIMATION2_DEMO'], CPPPATH = CPPPATH)

Return('group')
