/*
 *  Rockchip driver for RK ISP 1.1
 * (Based on Intel driver for sofiaxxx)
 *
 * Copyright (C) 2015 Intel Mobile Communications GmbH
 * Copyright (C) 2016 Fuzhou Rockchip Electronics Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author            Notes
 * 2020-7-20       ISP_TEAM     first implementation
 *
 */

#ifndef _RK_ISP_REG_H
#define _RK_ISP_REG_H

#if defined(RT_USING_ISP)

#define __raw_readl(p)                                  (*(volatile unsigned int *)(p))
#define __raw_writel(v,p)                               (*(volatile unsigned int *)(p) = (v))

#define WRITE_RKISP_REG(val, addr)                      __raw_writel(val, addr)
#define WRITE_CSIPHY_REG(addr, val)                     __raw_writel(val, addr)
#define READ_RKISP_REG(addr)                            __raw_readl(addr)
#define WRITE_RKISP_REG_OR(val, addr)                   __raw_writel((READ_RKISP_REG(addr)| val), addr)
#define WRITE_RKISP_REG_AND(val, addr)                  __raw_writel((READ_RKISP_REG(addr)& val), addr)
#define WRITE_RKISP_REG_VERIFY(d, a, mask) \
    { \
        unsigned i = 0; \
        unsigned long flags = 0; \
        /* spin_lock_irqsave(&iowrite32_verify_lock, flags);  xuhf@rock-chips.com: v1.0.1 */ \
        do { \
            WRITE_RKISP_REG(d, a); \
            if (i++ == 50) { \
                rt_kprintf("Error in writing %x@0x%p, read %x\n", \
                    (d) & (mask), a, READ_RKISP_REG(a)); \
            } \
        } while ((READ_RKISP_REG(a) & mask) != ((d) & mask)); \
        /* spin_unlock_irqrestore(&iowrite32_verify_lock, flags);  xuhf@rock-chips.com: v1.0.1 */ \
    }

#define WRITE_RKISP_REG_OR_VERIFY(d, a, mask) \
    WRITE_RKISP_REG_VERIFY((d) | READ_RKISP_REG(a), a, mask)
#define WRITE_RKISP_REG_AND_VERIFY(d, a, mask) \
    WRITE_RKISP_REG_VERIFY((d) & READ_RKISP_REG(a), a, mask)

#define ARRAY_SIZE(arr)     ( sizeof(arr) / sizeof((arr)[0]) )

/* ISP_CTRL */
#define RK_ISP_CTRL_ISP_ENABLE                  (1<<0)
#define RK_ISP_CTRL_ISP_MODE_RAW_PICT           (0<<1)
#define RK_ISP_CTRL_ISP_MODE_ITU656             (1<<1)
#define RK_ISP_CTRL_ISP_MODE_ITU601             (2<<1)
#define RK_ISP_CTRL_ISP_MODE_BAYER_ITU601       (3<<1)
#define RK_ISP_CTRL_ISP_MODE_DATA_MODE          (4<<1)
#define RK_ISP_CTRL_ISP_MODE_BAYER_ITU656       (5<<1)
#define RK_ISP_CTRL_ISP_MODE_RAW_PICT_ITU656    (6<<1)
#define RK_ISP_CTRL_ISP_INFORM_ENABLE           (1<<4)
#define RK_ISP_CTRL_ISP_GAMMA_IN_ENA            (1<<6)
#define RK_ISP_CTRL_ISP_GAMMA_IN_DIS            (0<<6)
#define RK_ISP_CTRL_ISP_AWB_ENA                 (1<<7)
#define RK_ISP_CTRL_ISP_AWB_DIS                 (0<<7)
#define RK_ISP_CTRL_ISP_CFG_UPD_PERMANENT       (1<<8)
#define RK_ISP_CTRL_ISP_CFG_UPD                 (1<<9)
#define RK_ISP_CTRL_ISP_GEN_CFG_UPD             (1<<10)
#define RK_ISP_CTRL_ISP_GAMMA_OUT_ENA           (1<<11)
#define RK_ISP_CTRL_ISP_GAMMA_OUT_DIS           (0<<11)
#define RK_ISP_CTRL_ISP_FLASH_MODE_ENA          (1<<12)
#define RK_ISP_CTRL_ISP_FLASH_MODE_DIS          (0<<12)
#define RK_ISP_CTRL_ISP_CSM_Y_FULL_ENA          (1<<13)
#define RK_ISP_CTRL_ISP_CSM_C_FULL_ENA          (1<<14)
#define RK_ISP_CTRL_ISP_GAMMA_OUT_12BIT_EN      (1<<19)
#define RK_ISP_CTRL_ISP_Y12_Y_OUT_EN            (1<<24)
#define RK_ISP_CTRL_ISP_Y12_UV_OUT_EN           (1<<25)
#define RK_ISP_CTRL_ISP_RGB_OUT_SEL             (1<<26)

/* ISP_ACQ_PROP */
#define RK_ISP_ACQ_PROP_NEG_EDGE                (0<<0)
#define RK_ISP_ACQ_PROP_POS_EDGE                (1<<0)
#define RK_ISP_ACQ_PROP_HSYNC_HIGH              (0<<1)
#define RK_ISP_ACQ_PROP_HSYNC_LOW               (1<<1)
#define RK_ISP_ACQ_PROP_VSYNC_HIGH              (0<<2)
#define RK_ISP_ACQ_PROP_VSYNC_LOW               (1<<2)
#define RK_ISP_ACQ_PROP_BAYER_PAT_RGGB          (0<<3)
#define RK_ISP_ACQ_PROP_BAYER_PAT_GRBG          (1<<3)
#define RK_ISP_ACQ_PROP_BAYER_PAT_GBRG          (2<<3)
#define RK_ISP_ACQ_PROP_BAYER_PAT_BGGR          (3<<3)
#define RK_ISP_ACQ_PROP_YCBYCR                  (0<<7)
#define RK_ISP_ACQ_PROP_YCRYCB                  (1<<7)
#define RK_ISP_ACQ_PROP_CBYCRY                  (2<<7)
#define RK_ISP_ACQ_PROP_CRYCBY                  (3<<7)
#define RK_ISP_ACQ_PROP_FIELD_SEL_ALL           (0<<9)
#define RK_ISP_ACQ_PROP_FIELD_SEL_EVEN          (1<<9)
#define RK_ISP_ACQ_PROP_FIELD_SEL_ODD           (2<<9)
#define RK_ISP_ACQ_PROP_IN_SEL_12B              (0<<12)
#define RK_ISP_ACQ_PROP_IN_SEL_10B_ZERO         (1<<12)
#define RK_ISP_ACQ_PROP_IN_SEL_10B_MSB          (2<<12)
#define RK_ISP_ACQ_PROP_IN_SEL_8B_ZERO          (3<<12)
#define RK_ISP_ACQ_PROP_IN_SEL_8B_MSB           (4<<12)
#define RK_ISP_ACQ_PROP_Y12_UV_DS_MODE_YUV420   (0<<19)
#define RK_ISP_ACQ_PROP_Y12_UV_DS_MODE_YUV422   (1<<19)
#define RK_ISP_ACQ_PROP_Y12_UV_DOWN_SAMPLE      (0<<17)

/* VI_DPCL */
#define RK_VI_DPCL_DMA_JPEG                     (0<<0)
#define RK_VI_DPCL_MP_MUX_MRSZ_MI               (1<<0)
#define RK_VI_DPCL_MP_MUX_MRSZ_JPEG             (2<<0)
#define RK_VI_DPCL_CHAN_MODE_MP                 (1<<2)
#define RK_VI_DPCL_CHAN_MODE_SP                 (2<<2)
#define RK_VI_DPCL_CHAN_MODE_MPSP               (3<<2)
#define RK_VI_DPCL_DMA_SW_SPMUX                 (0<<4)
#define RK_VI_DPCL_DMA_SW_SI                    (1<<4)
#define RK_VI_DPCL_DMA_SW_IE                    (2<<4)
#define RK_VI_DPCL_DMA_SW_JPEG                  (3<<4)
#define RK_VI_DPCL_DMA_SW_ISP                   (4<<4)
#define RK_VI_DPCL_IF_SEL_PARALLEL              (0<<8)
#define RK_VI_DPCL_IF_SEL_SMIA                  (1<<8)
#define RK_VI_DPCL_IF_SEL_MIPI                  (2<<8)
#define RK_VI_DPCL_DMA_IE_MUX_RK                (0<<10)
#define RK_VI_DPCL_DMA_IE_MUX_DMA               (1<<10)
#define RK_VI_DPCL_DMA_SP_MUX_RK                (0<<11)
#define RK_VI_DPCL_DMA_SP_MUX_DMA               (1<<11)

/* ISP_IMSC - ISP_MIS - ISP_RIS - ISP_ICR - ISP_ISR */
#define RK_ISP_OFF                              (1<<0)
#define RK_ISP_FRAME                            (1<<1)
#define RK_ISP_DATA_LOSS                        (1<<2)
#define RK_ISP_PIC_SIZE_ERROR                   (1<<3)
#define RK_ISP_AWB_DONE                         (1<<4)
#define RK_ISP_FRAME_IN                         (1<<5)
#define RK_ISP_V_START                          (1<<6)
#define RK_ISP_H_START                          (1<<7)
#define RK_ISP_FLASH_ON                         (1<<8)
#define RK_ISP_FLASH_OFF                        (1<<9)
#define RK_ISP_SHUTTER_ON                       (1<<10)
#define RK_ISP_SHUTTER_OFF                      (1<<11)
#define RK_ISP_AFM_SUM_OF                       (1<<12)
#define RK_ISP_AFM_LUM_OF                       (1<<13)
#define RK_ISP_AFM_FIN                          (1<<14)
#define RK_ISP_HIST_MEASURE_RDY                 (1<<15)
#define RK_ISP_FLASH_CAP                        (1<<17)
#define RK_ISP_EXP_END                          (1<<18)
#define RK_ISP_VSM_END                          (1<<19)

/* ISP_ERR */
#define RK_ISP_ERR_INFORM_SIZE                  (1 << 0)
#define RK_ISP_ERR_IS_SIZE                      (1 << 1)
#define RK_ISP_ERR_OUTFORM_SIZE                 (1 << 2)

/* MI_CTRL */
#define RK_MI_CTRL_MP_ENABLE_IN                 (1<<0)
#define RK_MI_CTRL_MP_ENABLE_OUT                (1<<16)
#define RK_MI_CTRL_MP_DISABLE                   (0<<0)
#define RK_MI_CTRL_SP_ENABLE                    (1<<1)
#define RK_MI_CTRL_SP_DISABLE                   (0<<1)
#define RK_MI_CTRL_JPEG_ENABLE                  (1<<2)
#define RK_MI_CTRL_JPEG_DISABLE                 (0<<2)
#define RK_MI_CTRL_RAW_ENABLE                   (1<<3)
#define RK_MI_CTRL_RAW_DISABLE                  (0<<3)
#define RK_MI_CTRL_HFLIP                        (1<<4)
#define RK_MI_CTRL_VFLIP                        (1<<5)
#define RK_MI_CTRL_ROT                          (1<<6)
#define RK_MI_BYTE_SWAP                         (1<<7)
#define RK_MI_NO_BYTE_SWAP                      (0<<7)
#define RK_MI_SP_Y_FULL_YUV2RGB                 (1 << 8)
#define RK_MI_SP_Y_REDUCED_YUV2RGB              (0 << 8)
#define RK_MI_SP_CBCR_FULL_YUV2RGB              (1 << 9)
#define RK_MI_SP_CBCR_REDUCED_YUV2RGB           (0 << 9)
#define RK_MI_SP_422NONCOSITEED                 (1 << 10)
#define RK_MI_MP_PINGPONG_ENABEL                (1 << 11)
#define RK_MI_MP_PINGPONG_DISABEL               (0 << 11)
#define RK_MI_SP_PINGPONG_ENABEL                (1 << 12)
#define RK_MI_SP_PINGPONG_DISABEL               (0 << 12)
#define RK_MI_MP_AUTOUPDATE_ENABLE              (1 << 13)
#define RK_MI_MP_AUTOUPDATE_DISABLE             (0 << 13)
#define RK_MI_SP_AUTOUPDATE_ENABLE              (1 << 14)
#define RK_MI_SP_AUTOUPDATE_DISABLE             (0 << 14)
#define RK_MI_LAST_PIXEL_SIG_ENABLE             (1 << 15)
#define RK_MI_LAST_PIXEL_SIG_DISABLE            (0 << 15)
#define RK_MI_CTRL_BURST_LEN_LUM_16             (0<<16)
#define RK_MI_CTRL_BURST_LEN_LUM_32             (1<<16)
#define RK_MI_CTRL_BURST_LEN_LUM_64             (2<<16)
#define RK_MI_CTRL_BURST_LEN_CHROM_16           (0<<18)
#define RK_MI_CTRL_BURST_LEN_CHROM_32           (1<<18)
#define RK_MI_CTRL_BURST_LEN_CHROM_64           (2<<18)
#define RK_MI_CTRL_INIT_BASE_EN                 (1<<20)
#define RK_MI_CTRL_INIT_BASE_DIS                (0<<20)
#define RK_MI_CTRL_INIT_OFFSET_EN               (1<<21)
#define RK_MI_CTRL_INIT_OFFSET_DIS              (0<<21)
#define RKMI_CTRL_MP_WRITE_FMT(a)               ((a)<<22)
#define RK_MI_CTRL_MP_WRITE_FMT_PLA             (0<<22)
#define RK_MI_CTRL_MP_WRITE_FMT_SPLA            (1<<22)
#define RK_MI_CTRL_MP_WRITE_FMT_INT             (2<<22)
#define RKMI_CTRL_SP_WRITE_FMT(a)               ((a)<<24)
#define RK_MI_CTRL_SP_WRITE_FMT_PLA             (0<<24)
#define RK_MI_CTRL_SP_WRITE_FMT_SPLA            (1<<24)
#define RK_MI_CTRL_SP_WRITE_FMT_INT             (2<<24)
#define RK_MI_CTRL_SP_INPUT_FMT_YUV400          (0<<26)
#define RK_MI_CTRL_SP_INPUT_FMT_YUV420          (1<<26)
#define RK_MI_CTRL_SP_INPUT_FMT_YUV422          (2<<26)
#define RK_MI_CTRL_SP_INPUT_FMT_YUV444          (3<<26)
#define RK_MI_CTRL_SP_OUTPUT_FMT_YUV400         (0<<28)
#define RK_MI_CTRL_SP_OUTPUT_FMT_YUV420         (1<<28)
#define RK_MI_CTRL_SP_OUTPUT_FMT_YUV422         (2<<28)
#define RK_MI_CTRL_SP_OUTPUT_FMT_YUV444         (3<<28)
#define RK_MI_CTRL_SP_OUTPUT_FMT_RGB565         (4<<28)
#define RK_MI_CTRL_SP_OUTPUT_FMT_RGB666         (5<<28)
#define RK_MI_CTRL_SP_OUTPUT_FMT_RGB888         (6<<28)

#define RK_MI_CTRL_HFLIP_SHIFT                  4
#define RK_MI_CTRL_VFLIP_SHIFT                  5

/* MI_INIT */
#define RK_MI_INIT_Y12_Y_EN                     (1<<0)
#define RK_MI_INIT_Y12_UV_EN                    (1<<1)
#define RK_MI_INIT_SKIP                         (1<<2)
#define RK_MI_INIT_Y12_ENDIAN_MODE_LITTLE       (0<<3)
#define RK_MI_INIT_Y12_ENDIAN_MODE_BIG          (1<<3)
#define RK_MI_INIT_SOFT_UPD                     (1<<4)
#define RK_MI_INIT_UPDATE_MODE_OLD              (0<<5)
#define RK_MI_INIT_UPDATE_MODE_NEW              (1<<5)

/* RSZ_CTRL */
#define RK_RSZ_CTRL_SCALE_HY_ENABLE             (1<<0)
#define RK_RSZ_CTRL_SCALE_HC_ENABLE             (1<<1)
#define RK_RSZ_CTRL_SCALE_VY_ENABLE             (1<<2)
#define RK_RSZ_CTRL_SCALE_VC_ENABLE             (1<<3)
#define RK_RSZ_CTRL_SCALE_HY_UP                 (1<<4)
#define RK_RSZ_CTRL_SCALE_HC_UP                 (1<<5)
#define RK_RSZ_CTRL_SCALE_VY_UP                 (1<<6)
#define RK_RSZ_CTRL_SCALE_VC_UP                 (1<<7)
#define RK_RSZ_CTRL_CFG_UPD                     (1<<8)
#define RK_RSZ_CTRL_CFG_UPD_AUTO                (1<<9)
#define RK_RSZ_SCALER_BYPASS                    (1<<16)

/* MI_IMSC - MI_MIS - MI_RIS - MI_ICR - MI_ISR */
#define RK_MI_NOTHING                           (0<<0)
#define RK_MI_MP_FRAME                          (1<<0)
#define RK_MI_SP_FRAME                          (1<<1)
#define RK_MI_MBLK_LINE                         (1<<2)
#define RK_MI_FILL_MP_Y                         (1<<3)
#define RK_MI_WRAP_MP_Y                         (1<<4)
#define RK_MI_WRAP_MP_CB                        (1<<5)
#define RK_MI_WRAP_MP_CR                        (1<<6)
#define RK_MI_WRAP_SP_Y                         (1<<7)
#define RK_MI_WRAP_SP_CB                        (1<<8)
#define RK_MI_WRAP_SP_CR                        (1<<9)
#define RK_MI_DMA_READY                         (1<<11)
#define RK_MI_Y12_Y_FRAME                       (1<<12)
#define RK_MI_Y12_UV_FRAME                      (1<<13)
#define RK_MI_ALL_FRAME                         (1<<14)


/* MI_STATUS */
#define RK_MI_STATUS_MP_Y_FIFO_FULL             (1<<0)
#define RK_MI_STATUS_SP_Y_FIFO_FULL             (1<<4)

/* MI_DMA_CTRL */
#define RK_MI_DMA_CTRL_BURST_LEN_LUM_16         (0<<0)
#define RK_MI_DMA_CTRL_BURST_LEN_LUM_32         (1<<0)
#define RK_MI_DMA_CTRL_BURST_LEN_LUM_64         (2<<0)
#define RK_MI_DMA_CTRL_BURST_LEN_CHROM_16       (0<<2)
#define RK_MI_DMA_CTRL_BURST_LEN_CHROM_32       (1<<2)
#define RK_MI_DMA_CTRL_BURST_LEN_CHROM_64       (2<<2)
#define RKMI_DMA_CTRL_READ_FMT(a)               ((a)<<4)
#define RK_MI_DMA_CTRL_READ_FMT_PLANAR          (0<<4)
#define RK_MI_DMA_CTRL_READ_FMT_SPLANAR         (1<<4)
#define RK_MI_DMA_CTRL_READ_FMT_PACKED          (2<<4)
#define RK_MI_DMA_CTRL_FMT_YUV444               (3<<6)
#define RK_MI_DMA_CTRL_FMT_YUV422               (2<<6)
#define RK_MI_DMA_CTRL_FMT_YUV420               (1<<6)
#define RK_MI_DMA_CTRL_FMT_YUV400               (0<<6)
#define RK_MI_DMA_CTRL_BYTE_SWAP                (1<<8)
#define RK_MI_DMA_CTRL_NO_BYTE_SWAP             (0<<8)
#define RK_MI_DMA_CTRL_CONTINOUS_ENA            (1<<9)
#define RK_MI_DMA_CTRL_CONTINOUS_DIS            (0<<9)
#define RK_MI_DMA_CTRL_RGB_BAYER_NO             (0<<12)
#define RK_MI_DMA_CTRL_RGB_BAYER_8BIT           (1<<12)
#define RK_MI_DMA_CTRL_RGB_BAYER_16BIT          (2<<12)
/* MI_DMA_START */
#define RK_MI_DMA_START_ENABLE                  (1<<0)
/* MI_XTD_FORMAT_CTRL  */
#define RK_MI_XTD_FMT_CTRL_MP_CB_CR_SWAP        (1<<0)
#define RK_MI_XTD_FMT_CTRL_SP_CB_CR_SWAP        (1<<1)
#define RK_MI_XTD_FMT_CTRL_DMA_CB_CR_SWAP       (1<<2)
#define RK_MI_XTD_FMT_CTRL_Y12_CB_CR_SWAP       (1<<3)

#define RK_MI_ADDR_SIZE_ALIGN_MASK              0xfffffff8

/* CCL */
#define RK_CCL_RK_CLK_ENA                       (0<<2)
#define RK_CCL_RK_CLK_DIS                       (1<<2)
/* ICCL */
#define RK_ICCL_ISP_CLK                         (1<<0)
#define RK_ICCL_CP_CLK                          (1<<1)
#define RK_ICCL_RES_2                           (1<<2)
#define RK_ICCL_MRSZ_CLK                        (1<<3)
#define RK_ICCL_SRSZ_CLK                        (1<<4)
#define RK_ICCL_JPEG_CLK                        (1<<5)
#define RK_ICCL_MI_CLK                          (1<<6)
#define RK_ICCL_RES_7                           (1<<7)
#define RK_ICCL_IE_CLK                          (1<<8)
#define RK_ICCL_SIMP_CLK                        (1<<9)
#define RK_ICCL_SMIA_CLK                        (1<<10)
#define RK_ICCL_MIPI_CLK                        (1<<11)
#define RK_ICCL_ALL_CLK                         (-1)
#define RK_ICCL_NO_CLK                          (0)
/* IRCL */
#define RK_IRCL_ISP_SW_RST                      (1<<0)
#define RK_IRCL_CP_SW_RST                       (1<<1)
#define RK_IRCL_YCS_SW_RST                      (1<<2)
#define RK_IRCL_MRSZ_SW_RST                     (1<<3)
#define RK_IRCL_SRSZ_SW_RST                     (1<<4)
#define RK_IRCL_JPEG_SW_RST                     (1<<5)
#define RK_IRCL_MI_SW_RST                       (1<<6)
#define RK_IRCL_RK_SW_RST                       (1<<7)
#define RK_IRCL_IE_SW_RST                       (1<<8)
#define RK_IRCL_SI_SW_RST                       (1<<9)
#define RK_IRCL_MIPI_SW_RST                     (1<<11)

/* C_PROC_CTR */
#define RK_C_PROC_CTR_ENABLE                    (1<<0)
#define RK_C_PROC_CTR_DIS                       (0<<0)
#define RK_C_PROC_YOUT_FULL                     (1<<1)
#define RK_C_PROC_YOUT_LIM                      (0<<1)
#define RK_C_PROC_YIN_FULL                      (1<<2)
#define RK_C_PROC_YIN_LIM                       (0<<2)
#define RK_C_PROC_COUT_FULL                     (1<<3)
#define RK_C_PROC_COUT_LIM                      (0<<3)

/* DUAL_CROP_CTRL */
#define RK_DUAL_CROP_MP_MODE_BYPASS             (0 << 0)
#define RK_DUAL_CROP_MP_MODE_YUV                (1 << 0)
#define RK_DUAL_CROP_MP_MODE_RAW                (2 << 0)
#define RK_DUAL_CROP_SP_MODE_BYPASS             (0 << 2)
#define RK_DUAL_CROP_SP_MODE_YUV                (1 << 2)
#define RK_DUAL_CROP_SP_MODE_RAW                (2 << 2)
#define RK_DUAL_CROP_CFG_UPD_PERMANENT          (1 << 4)
#define RK_DUAL_CROP_CFG_UPD                    (1 << 5)
#define RK_DUAL_CROP_GEN_CFG_UPD                (1 << 6)

/* IMG_EFF_CTRL */
#define RK_IMG_EFF_CTRL_ENABLE                  (1<<0)
#define RK_IMG_EFF_CTRL_MODE_BLACKWHITE         (0<<1)
#define RK_IMG_EFF_CTRL_MODE_NEGATIVE           (1<<1)
#define RK_IMG_EFF_CTRL_MODE_SEPIA              (2<<1)
#define RK_IMG_EFF_CTRL_MODE_COLOR_SEL          (3<<1)
#define RK_IMG_EFF_CTRL_MODE_EMBOSS             (4<<1)
#define RK_IMG_EFF_CTRL_MODE_SKETCH             (5<<1)
#define RK_IMG_EFF_CTRL_MODE_SHARPEN            (6<<1)
#define RK_IMG_EFF_CTRL_CFG_UPD                 (1<<4)
#define RK_IMG_EFF_CTRL_YCBCR_FULL              (1<<5)

#define RK_IMG_EFF_CTRL_MODE_BLACKWHITE_SHIFT   (0)
#define RK_IMG_EFF_CTRL_MODE_NEGATIVE_SHIFT     (1)
#define RK_IMG_EFF_CTRL_MODE_SEPIA_SHIFT        (2)
#define RK_IMG_EFF_CTRL_MODE_COLOR_SEL_SHIFT    (3)
#define RK_IMG_EFF_CTRL_MODE_EMBOSS_SHIFT       (4)
#define RK_IMG_EFF_CTRL_MODE_SKETCH_SHIFT       (5)
#define RK_IMG_EFF_CTRL_MODE_SHARPEN_SHIFT      (6)

/* IMG_EFF_COLOR_SEL */
#define RK_IMG_EFF_COLOR_RGB                    (0<<0)
#define RK_IMG_EFF_COLOR_B                      (1<<0)
#define RK_IMG_EFF_COLOR_G                      (2<<0)
#define RK_IMG_EFF_COLOR_GB                     (3<<0)
#define RK_IMG_EFF_COLOR_R                      (4<<0)
#define RK_IMG_EFF_COLOR_RB                     (5<<0)
#define RK_IMG_EFF_COLOR_RG                     (6<<0)
#define RK_IMG_EFF_COLOR_RGB2                   (7<<0)

/* MIPI */

/* MIPI_DPHY1 */


/* MIPI_DPHY2 */


/* MIPI_CTRL */
#define RK_MIPI_CTRL_OUTPUT_ENA             (1<<0)
#define RKMIPI_CTRL_SHUTDOWNLANES(a)        ((a)<<8)
#define RK_CSI_LANE_2                       (1<<1)
#define RK_CSI_LANE_3                       (1<<2)
#define RK_CSI_LANE_4                       (1<<3)
#define RKMIPI_CTRL_NUM_LANES(a)            ((a)<<12)
#define RK_MIPI_CTRL_ERR_SOT_HS_ENA         (0<<16)
#define RK_MIPI_CTRL_ERR_SOT_HS_SKIP        (1<<16)
#define RK_MIPI_CTRL_ERR_SOT_SYNC_HS_ENA    (0<<17)
#define RK_MIPI_CTRL_ERR_SOT_SYNC_HS_SKIP   (1<<17)
#define RK_MIPI_CTRL_CLOCKLANE_ENA          (1<<18)

/* MIPI_DATA_SEL */
#define RKMIPI_DATA_SEL_VC(a)               ((a)<<6)
#define RKMIPI_DATA_SEL_DT(a)               ((a)<<0)

#define RK_MIPI_INTERRUPT_ALL               (-1)

/* MIPI_IMSC, MIPI_RIS, MIPI_MIS, MIPI_ICR, MIPI_ISR */
#define RKMIPI_SYNC_FIFO_OVFLW(a)           ((a)<<0)
#define RKMIPI_ERR_SOT(a)                   ((a)<<4)
#define RKMIPI_ERR_SOT_SYNC(a)              ((a)<<8)
#define RKMIPI_ERR_EOT_SYNC(a)              ((a)<<12)
#define RKMIPI_ERR_CTRL(a)                  ((a)<<16)
#define RK_MIPI_ERR_PROTOCOL                (1<<20)
#define RK_MIPI_ERR_ECC1                    (1<<21)
#define RK_MIPI_ERR_ECC2                    (1<<22)
#define RK_MIPI_ERR_CS                      (1<<23)
#define RK_MIPI_FRAME_END                   (1<<24)
#define RK_MIPI_ADD_DATA_OVFLW              (1<<25)
#define RK_MIPI_ADD_DATA_WATER_MARK         (1<<26)

#define RK_MIPI_ERR_CSI                     (RK_MIPI_ERR_PROTOCOL| \
                                             RK_MIPI_ERR_ECC1| \
                                             RK_MIPI_ERR_ECC2| \
                                             RK_MIPI_ERR_CS)

#define RK_MIPI_ERR_DPHY                    (RKMIPI_ERR_SOT(3)| \
                                             RKMIPI_ERR_SOT_SYNC(3)| \
                                             RKMIPI_ERR_EOT_SYNC(3)| \
                                             RKMIPI_ERR_CTRL(3))

/* SUPER_IMPOSE */
#define RK_SUPER_IMP_CTRL_NORMAL_MODE        (1<<0)
#define RK_SUPER_IMP_CTRL_BYPASS_MODE        (0<<0)
#define RK_SUPER_IMP_CTRL_REF_IMG_MEM        (1<<1)
#define RK_SUPER_IMP_CTRL_REF_IMG_IE         (0<<1)
#define RK_SUPER_IMP_CTRL_TRANSP_DIS         (1<<2)
#define RK_SUPER_IMP_CTRL_TRANSP_ENA         (0<<2)

/* ISP HISTOGRAM CALCULATION : ISP_HIST_PROP */
#define RKISP_HIST_PROP_PDIV(a)             ((a)<<3)
#define RK_ISP_HIST_PROP_MODE_DIS           (0<<0)
#define RK_ISP_HIST_PROP_MODE_RGB           (1<<0)
#define RK_ISP_HIST_PROP_MODE_RED           (2<<0)
#define RK_ISP_HIST_PROP_MODE_GREEN         (3<<0)
#define RK_ISP_HIST_PROP_MODE_BLUE          (4<<0)
#define RK_ISP_HIST_PROP_MODE_LUM           (5<<0)

/* AUTO FOCUS MEASUREMENT:  ISP_AFM_CTRL */
#define ISP_AFM_CTRL_ENABLE                 (1<<0)
#define ISP_AFM_CTRL_DISABLE                (0<<0)

/* SHUTTER CONTROL */
#define RK_ISP_SH_CTRL_SH_ENA               (1<<0)
#define RK_ISP_SH_CTRL_SH_DIS               (0<<0)
#define RK_ISP_SH_CTRL_REP_EN               (1<<1)
#define RK_ISP_SH_CTRL_REP_DIS              (0<<1)
#define RK_ISP_SH_CTRL_SRC_SH_TRIG          (1<<2)
#define RK_ISP_SH_CTRL_SRC_VSYNC            (0<<2)
#define RK_ISP_SH_CTRL_EDGE_POS             (1<<3)
#define RK_ISP_SH_CTRL_EDGE_NEG             (0<<3)
#define RK_ISP_SH_CTRL_POL_LOW              (1<<4)
#define RK_ISP_SH_CTRL_POL_HIGH             (0<<4)

/* FLASH MODULE */
/* ISP_FLASH_CMD */
#define RK_FLASH_CMD_PRELIGHT_ON            (1<<0)
#define RK_FLASH_CMD_PRELIGHT_OFF           (0<<0)
#define RK_FLASH_CMD_FLASH_ON               (1<<1)
#define RK_FLASH_CMD_FLASH_OFF              (0<<1)
#define RK_FLASH_CMD_PRE_FLASH_ON           (1<<2)
#define RK_FLASH_CMD_PRE_FLASH_OFF          (0<<2)
/* ISP_FLASH_CONFIG */
#define RK_FLASH_CONFIG_PRELIGHT_BEG        (0<<1)
#define RK_FLASH_CONFIG_PRELIGHT_END        (1<<0)
#define RK_FLASH_CONFIG_VSYNC_NEG           (0<<1)
#define RK_FLASH_CONFIG_VSYNC_POS           (1<<1)
#define RK_FLASH_CONFIG_PRELIGHT_HIGH       (0<<2)
#define RK_FLASH_CONFIG_PRELIGHT_LOW        (1<<2)
#define RK_FLASH_CONFIG_SRC_VSYNC           (0<<3)
#define RK_FLASH_CONFIG_SRC_FL_TRIG         (1<<3)
#define RK_FLASH_CONFIG_DELAY(a)            ((a)<<4)

/* BAD PIXEL DETECTION */

/* =================================================================== */
/*                            RK Registers                            */
/* =================================================================== */
#define RK_CTRL_BASE                        (0x40170000U)
#define RK_CCL                              ((RK_CTRL_BASE + 0x00000000))
#define RK_VI_ID                            ((RK_CTRL_BASE + 0x00000008))
#define RK_ICCL                             ((RK_CTRL_BASE + 0x00000010))
#define RK_IRCL                             ((RK_CTRL_BASE + 0x00000014))
#define RK_VI_DPCL                          ((RK_CTRL_BASE + 0x00000018))

#define RK_IMG_EFF_BASE                     (0x40170200U)
#define RK_IMG_EFF_CTRL                     ((RK_IMG_EFF_BASE + 0x00000000))
#define RK_IMG_EFF_COLOR_SEL                ((RK_IMG_EFF_BASE + 0x00000004))
#define RK_IMG_EFF_MAT_1                    ((RK_IMG_EFF_BASE + 0x00000008))
#define RK_IMG_EFF_MAT_2                    ((RK_IMG_EFF_BASE + 0x0000000C))
#define RK_IMG_EFF_MAT_3                    ((RK_IMG_EFF_BASE + 0x00000010))
#define RK_IMG_EFF_MAT_4                    ((RK_IMG_EFF_BASE + 0x00000014))
#define RK_IMG_EFF_MAT_5                    ((RK_IMG_EFF_BASE + 0x00000018))
#define RK_IMG_EFF_TINT                     ((RK_IMG_EFF_BASE + 0x0000001C))
#define RK_IMG_EFF_CTRL_SHD                 ((RK_IMG_EFF_BASE + 0x00000020))
#define RK_IMG_EFF_SHARPEN                  ((RK_IMG_EFF_BASE + 0x00000024))

#define RK_SUPER_IMP_BASE                   (0x40170300U)
#define RK_SUPER_IMP_CTRL                   ((RK_SUPER_IMP_BASE + 0x00000000))
#define RK_SUPER_IMP_OFFSET_X               ((RK_SUPER_IMP_BASE + 0x00000004))
#define RK_SUPER_IMP_OFFSET_Y               ((RK_SUPER_IMP_BASE + 0x00000008))
#define RK_SUPER_IMP_COLOR_Y                ((RK_SUPER_IMP_BASE + 0x0000000C))
#define RK_SUPER_IMP_COLOR_CB               ((RK_SUPER_IMP_BASE + 0x00000010))
#define RK_SUPER_IMP_COLOR_CR               ((RK_SUPER_IMP_BASE + 0x00000014))

#define RK_ISP_BASE                         (0x40170400U)
#define RK_ISP_CTRL                         ((RK_ISP_BASE + 0x00000000))
#define RK_ISP_ACQ_PROP                     ((RK_ISP_BASE + 0x00000004))
#define RK_ISP_ACQ_H_OFFS                   ((RK_ISP_BASE + 0x00000008))
#define RK_ISP_ACQ_V_OFFS                   ((RK_ISP_BASE + 0x0000000C))
#define RK_ISP_ACQ_H_SIZE                   ((RK_ISP_BASE + 0x00000010))
#define RK_ISP_ACQ_V_SIZE                   ((RK_ISP_BASE + 0x00000014))
#define RK_ISP_ACQ_NR_FRAMES                ((RK_ISP_BASE + 0x00000018))
#define RK_ISP_GAMMA_DX_LO                  ((RK_ISP_BASE + 0x0000001C))
#define RK_ISP_GAMMA_DX_HI                  ((RK_ISP_BASE + 0x00000020))
#define RK_ISP_GAMMA_R_Y0                   ((RK_ISP_BASE + 0x00000024))
#define RK_ISP_GAMMA_R_Y1                   ((RK_ISP_BASE + 0x00000028))
#define RK_ISP_GAMMA_R_Y2                   ((RK_ISP_BASE + 0x0000002C))
#define RK_ISP_GAMMA_R_Y3                   ((RK_ISP_BASE + 0x00000030))
#define RK_ISP_GAMMA_R_Y4                   ((RK_ISP_BASE + 0x00000034))
#define RK_ISP_GAMMA_R_Y5                   ((RK_ISP_BASE + 0x00000038))
#define RK_ISP_GAMMA_R_Y6                   ((RK_ISP_BASE + 0x0000003C))
#define RK_ISP_GAMMA_R_Y7                   ((RK_ISP_BASE + 0x00000040))
#define RK_ISP_GAMMA_R_Y8                   ((RK_ISP_BASE + 0x00000044))
#define RK_ISP_GAMMA_R_Y9                   ((RK_ISP_BASE + 0x00000048))
#define RK_ISP_GAMMA_R_Y10                  ((RK_ISP_BASE + 0x0000004C))
#define RK_ISP_GAMMA_R_Y11                  ((RK_ISP_BASE + 0x00000050))
#define RK_ISP_GAMMA_R_Y12                  ((RK_ISP_BASE + 0x00000054))
#define RK_ISP_GAMMA_R_Y13                  ((RK_ISP_BASE + 0x00000058))
#define RK_ISP_GAMMA_R_Y14                  ((RK_ISP_BASE + 0x0000005C))
#define RK_ISP_GAMMA_R_Y15                  ((RK_ISP_BASE + 0x00000060))
#define RK_ISP_GAMMA_R_Y16                  ((RK_ISP_BASE + 0x00000064))
#define RK_ISP_GAMMA_G_Y0                   ((RK_ISP_BASE + 0x00000068))
#define RK_ISP_GAMMA_G_Y1                   ((RK_ISP_BASE + 0x0000006C))
#define RK_ISP_GAMMA_G_Y2                   ((RK_ISP_BASE + 0x00000070))
#define RK_ISP_GAMMA_G_Y3                   ((RK_ISP_BASE + 0x00000074))
#define RK_ISP_GAMMA_G_Y4                   ((RK_ISP_BASE + 0x00000078))
#define RK_ISP_GAMMA_G_Y5                   ((RK_ISP_BASE + 0x0000007C))
#define RK_ISP_GAMMA_G_Y6                   ((RK_ISP_BASE + 0x00000080))
#define RK_ISP_GAMMA_G_Y7                   ((RK_ISP_BASE + 0x00000084))
#define RK_ISP_GAMMA_G_Y8                   ((RK_ISP_BASE + 0x00000088))
#define RK_ISP_GAMMA_G_Y9                   ((RK_ISP_BASE + 0x0000008C))
#define RK_ISP_GAMMA_G_Y10                  ((RK_ISP_BASE + 0x00000090))
#define RK_ISP_GAMMA_G_Y11                  ((RK_ISP_BASE + 0x00000094))
#define RK_ISP_GAMMA_G_Y12                  ((RK_ISP_BASE + 0x00000098))
#define RK_ISP_GAMMA_G_Y13                  ((RK_ISP_BASE + 0x0000009C))
#define RK_ISP_GAMMA_G_Y14                  ((RK_ISP_BASE + 0x000000A0))
#define RK_ISP_GAMMA_G_Y15                  ((RK_ISP_BASE + 0x000000A4))
#define RK_ISP_GAMMA_G_Y16                  ((RK_ISP_BASE + 0x000000A8))
#define RK_ISP_GAMMA_B_Y0                   ((RK_ISP_BASE + 0x000000AC))
#define RK_ISP_GAMMA_B_Y1                   ((RK_ISP_BASE + 0x000000B0))
#define RK_ISP_GAMMA_B_Y2                   ((RK_ISP_BASE + 0x000000B4))
#define RK_ISP_GAMMA_B_Y3                   ((RK_ISP_BASE + 0x000000B8))
#define RK_ISP_GAMMA_B_Y4                   ((RK_ISP_BASE + 0x000000BC))
#define RK_ISP_GAMMA_B_Y5                   ((RK_ISP_BASE + 0x000000C0))
#define RK_ISP_GAMMA_B_Y6                   ((RK_ISP_BASE + 0x000000C4))
#define RK_ISP_GAMMA_B_Y7                   ((RK_ISP_BASE + 0x000000C8))
#define RK_ISP_GAMMA_B_Y8                   ((RK_ISP_BASE + 0x000000CC))
#define RK_ISP_GAMMA_B_Y9                   ((RK_ISP_BASE + 0x000000D0))
#define RK_ISP_GAMMA_B_Y10                  ((RK_ISP_BASE + 0x000000D4))
#define RK_ISP_GAMMA_B_Y11                  ((RK_ISP_BASE + 0x000000D8))
#define RK_ISP_GAMMA_B_Y12                  ((RK_ISP_BASE + 0x000000DC))
#define RK_ISP_GAMMA_B_Y13                  ((RK_ISP_BASE + 0x000000E0))
#define RK_ISP_GAMMA_B_Y14                  ((RK_ISP_BASE + 0x000000E4))
#define RK_ISP_GAMMA_B_Y15                  ((RK_ISP_BASE + 0x000000E8))
#define RK_ISP_GAMMA_B_Y16                  ((RK_ISP_BASE + 0x000000EC))
#define RK_ISP_AWB_PROP                     ((RK_ISP_BASE+0x00000110))
#define RK_ISP_AWB_WND_H_OFFS               ((RK_ISP_BASE+0x00000114))
#define RK_ISP_AWB_WND_V_OFFS               ((RK_ISP_BASE+0x00000118))
#define RK_ISP_AWB_WND_H_SIZE               ((RK_ISP_BASE+0x0000011C))
#define RK_ISP_AWB_WND_V_SIZE               ((RK_ISP_BASE+0x00000120))
#define RK_ISP_AWB_FRAMES                   ((RK_ISP_BASE+0x00000124))
#define RK_ISP_AWB_REF                      ((RK_ISP_BASE+0x00000128))
#define RK_ISP_AWB_THRESH                   ((RK_ISP_BASE+0x0000012C))
#define RK_ISP_AWB_GAIN_G                   ((RK_ISP_BASE+0x00000138))
#define RK_ISP_AWB_GAIN_RB                  ((RK_ISP_BASE+0x0000013C))
#define RK_ISP_AWB_WHITE_CNT                ((RK_ISP_BASE+0x00000140))
#define RK_ISP_AWB_MEAN                     ((RK_ISP_BASE+0x00000144))
#define RK_ISP_CC_COEFF_0                   ((RK_ISP_BASE + 0x00000170))
#define RK_ISP_CC_COEFF_1                   ((RK_ISP_BASE + 0x00000174))
#define RK_ISP_CC_COEFF_2                   ((RK_ISP_BASE + 0x00000178))
#define RK_ISP_CC_COEFF_3                   ((RK_ISP_BASE + 0x0000017C))
#define RK_ISP_CC_COEFF_4                   ((RK_ISP_BASE + 0x00000180))
#define RK_ISP_CC_COEFF_5                   ((RK_ISP_BASE + 0x00000184))
#define RK_ISP_CC_COEFF_6                   ((RK_ISP_BASE + 0x00000188))
#define RK_ISP_CC_COEFF_7                   ((RK_ISP_BASE + 0x0000018C))
#define RK_ISP_CC_COEFF_8                   ((RK_ISP_BASE + 0x00000190))
#define RK_ISP_OUT_H_OFFS                   ((RK_ISP_BASE + 0x00000194))
#define RK_ISP_OUT_V_OFFS                   ((RK_ISP_BASE + 0x00000198))
#define RK_ISP_OUT_H_SIZE                   ((RK_ISP_BASE + 0x0000019C))
#define RK_ISP_OUT_V_SIZE                   ((RK_ISP_BASE + 0x000001A0))
#define RK_ISP_DEMOSAIC                     ((RK_ISP_BASE + 0x000001A4))
#define RK_ISP_FLAGS_SHD                    ((RK_ISP_BASE + 0x000001A8))
#define RK_ISP_OUT_H_OFFS_SHD               ((RK_ISP_BASE + 0x000001AC))
#define RK_ISP_OUT_V_OFFS_SHD               ((RK_ISP_BASE + 0x000001B0))
#define RK_ISP_OUT_H_SIZE_SHD               ((RK_ISP_BASE + 0x000001B4))
#define RK_ISP_OUT_V_SIZE_SHD               ((RK_ISP_BASE + 0x000001B8))
#define RK_ISP_IMSC                         ((RK_ISP_BASE + 0x000001BC))
#define RK_ISP_RIS                          ((RK_ISP_BASE + 0x000001C0))
#define RK_ISP_MIS                          ((RK_ISP_BASE + 0x000001C4))
#define RK_ISP_ICR                          ((RK_ISP_BASE + 0x000001C8))
#define RK_ISP_ISR                          ((RK_ISP_BASE + 0x000001CC))
#define RK_ISP_CT_COEFF_0                   ((RK_ISP_BASE + 0x000001D0))
#define RK_ISP_CT_COEFF_1                   ((RK_ISP_BASE + 0x000001D4))
#define RK_ISP_CT_COEFF_2                   ((RK_ISP_BASE + 0x000001D8))
#define RK_ISP_CT_COEFF_3                   ((RK_ISP_BASE + 0x000001DC))
#define RK_ISP_CT_COEFF_4                   ((RK_ISP_BASE + 0x000001E0))
#define RK_ISP_CT_COEFF_5                   ((RK_ISP_BASE + 0x000001E4))
#define RK_ISP_CT_COEFF_6                   ((RK_ISP_BASE + 0x000001E8))
#define RK_ISP_CT_COEFF_7                   ((RK_ISP_BASE + 0x000001EC))
#define RK_ISP_CT_COEFF_8                   ((RK_ISP_BASE + 0x000001F0))
#define RK_ISP_GAMMA_OUT_MODE               ((RK_ISP_BASE + 0x000001F4))
#define RK_ISP_GAMMA_OUT_Y_0                ((RK_ISP_BASE + 0x000001F8))
#define RK_ISP_GAMMA_OUT_Y_1                ((RK_ISP_BASE + 0x000001FC))
#define RK_ISP_GAMMA_OUT_Y_2                ((RK_ISP_BASE + 0x00000200))
#define RK_ISP_GAMMA_OUT_Y_3                ((RK_ISP_BASE + 0x00000204))
#define RK_ISP_GAMMA_OUT_Y_4                ((RK_ISP_BASE + 0x00000208))
#define RK_ISP_GAMMA_OUT_Y_5                ((RK_ISP_BASE + 0x0000020C))
#define RK_ISP_GAMMA_OUT_Y_6                ((RK_ISP_BASE + 0x00000210))
#define RK_ISP_GAMMA_OUT_Y_7                ((RK_ISP_BASE + 0x00000214))
#define RK_ISP_GAMMA_OUT_Y_8                ((RK_ISP_BASE + 0x00000218))
#define RK_ISP_GAMMA_OUT_Y_9                ((RK_ISP_BASE + 0x0000021C))
#define RK_ISP_GAMMA_OUT_Y_10               ((RK_ISP_BASE + 0x00000220))
#define RK_ISP_GAMMA_OUT_Y_11               ((RK_ISP_BASE + 0x00000224))
#define RK_ISP_GAMMA_OUT_Y_12               ((RK_ISP_BASE + 0x00000228))
#define RK_ISP_GAMMA_OUT_Y_13               ((RK_ISP_BASE + 0x0000022C))
#define RK_ISP_GAMMA_OUT_Y_14               ((RK_ISP_BASE + 0x00000230))
#define RK_ISP_GAMMA_OUT_Y_15               ((RK_ISP_BASE + 0x00000234))
#define RK_ISP_GAMMA_OUT_Y_16               ((RK_ISP_BASE + 0x00000238))
#define RK_ISP_ERR                          ((RK_ISP_BASE + 0x0000023C))
#define RK_ISP_ERR_CLR                      ((RK_ISP_BASE + 0x00000240))
#define RK_ISP_FRAME_COUNT                  ((RK_ISP_BASE + 0x00000244))
#define RK_ISP_CT_OFFSET_R                  ((RK_ISP_BASE + 0x00000248))
#define RK_ISP_CT_OFFSET_G                  ((RK_ISP_BASE + 0x0000024C))
#define RK_ISP_CT_OFFSET_B                  ((RK_ISP_BASE + 0x00000250))

#define RK_C_PROC_BASE                      (0x40170800U)
#define RK_C_PROC_CTRL                      ((RK_C_PROC_BASE + 0x00000000))
#define RK_C_PROC_CONTRAST                  ((RK_C_PROC_BASE + 0x00000004))
#define RK_C_PROC_BRIGHTNESS                ((RK_C_PROC_BASE + 0x00000008))
#define RK_C_PROC_SATURATION                ((RK_C_PROC_BASE + 0x0000000C))
#define RK_C_PROC_HUE                       ((RK_C_PROC_BASE + 0x00000010))

#define RK_DUAL_CROP_BASE                   (0x4170880)
#define RK_DUAL_CROP_CTRL                   (RK_DUAL_CROP_BASE + 0x00000000)
#define RK_DUAL_CROP_M_H_OFFS               (RK_DUAL_CROP_BASE + 0x00000004)
#define RK_DUAL_CROP_M_V_OFFS               (RK_DUAL_CROP_BASE + 0x00000008)
#define RK_DUAL_CROP_M_H_SIZE               (RK_DUAL_CROP_BASE + 0x0000000C)
#define RK_DUAL_CROP_M_V_SIZE               (RK_DUAL_CROP_BASE + 0x00000010)
#define RK_DUAL_CROP_S_H_OFFS               (RK_DUAL_CROP_BASE + 0x00000014)
#define RK_DUAL_CROP_S_V_OFFS               (RK_DUAL_CROP_BASE + 0x00000018)
#define RK_DUAL_CROP_S_H_SIZE               (RK_DUAL_CROP_BASE + 0x0000001C)
#define RK_DUAL_CROP_S_V_SIZE               (RK_DUAL_CROP_BASE + 0x00000020)
#define RK_DUAL_CROP_M_H_OFFS_SHD           (RK_DUAL_CROP_BASE + 0x00000024)
#define RK_DUAL_CROP_M_V_OFFS_SHD           (RK_DUAL_CROP_BASE + 0x00000028)
#define RK_DUAL_CROP_M_H_SIZE_SHD           (RK_DUAL_CROP_BASE + 0x0000002C)
#define RK_DUAL_CROP_M_V_SIZE_SHD           (RK_DUAL_CROP_BASE + 0x00000030)
#define RK_DUAL_CROP_S_H_OFFS_SHD           (RK_DUAL_CROP_BASE + 0x00000034)
#define RK_DUAL_CROP_S_V_OFFS_SHD           (RK_DUAL_CROP_BASE + 0x00000038)
#define RK_DUAL_CROP_S_H_SIZE_SHD           (RK_DUAL_CROP_BASE + 0x0000003C)
#define RK_DUAL_CROP_S_V_SIZE_SHD           (RK_DUAL_CROP_BASE + 0x00000040)

#define RK_MRSZ_BASE                        (0x40170C00U)
#define RK_MRSZ_CTRL                        ((RK_MRSZ_BASE + 0x00000000))
#define RK_MRSZ_SCALE_HY                    ((RK_MRSZ_BASE + 0x00000004))
#define RK_MRSZ_SCALE_HCB                   ((RK_MRSZ_BASE + 0x00000008))
#define RK_MRSZ_SCALE_HCR                   ((RK_MRSZ_BASE + 0x0000000C))
#define RK_MRSZ_SCALE_VY                    ((RK_MRSZ_BASE + 0x00000010))
#define RK_MRSZ_SCALE_VC                    ((RK_MRSZ_BASE + 0x00000014))
#define RK_MRSZ_PHASE_HY                    ((RK_MRSZ_BASE + 0x00000018))
#define RK_MRSZ_PHASE_HC                    ((RK_MRSZ_BASE + 0x0000001C))
#define RK_MRSZ_PHASE_VY                    ((RK_MRSZ_BASE + 0x00000020))
#define RK_MRSZ_PHASE_VC                    ((RK_MRSZ_BASE + 0x00000024))
#define RK_MRSZ_SCALE_LUT_ADDR              ((RK_MRSZ_BASE + 0x00000028))
#define RK_MRSZ_SCALE_LUT                   ((RK_MRSZ_BASE + 0x0000002C))
#define RK_MRSZ_CTRL_SHD                    ((RK_MRSZ_BASE + 0x00000030))
#define RK_MRSZ_SCALE_HY_SHD                ((RK_MRSZ_BASE + 0x00000034))
#define RK_MRSZ_SCALE_HCB_SHD               ((RK_MRSZ_BASE + 0x00000038))
#define RK_MRSZ_SCALE_HCR_SHD               ((RK_MRSZ_BASE + 0x0000003C))
#define RK_MRSZ_SCALE_VY_SHD                ((RK_MRSZ_BASE + 0x00000040))
#define RK_MRSZ_SCALE_VC_SHD                ((RK_MRSZ_BASE + 0x00000044))
#define RK_MRSZ_PHASE_HY_SHD                ((RK_MRSZ_BASE + 0x00000048))
#define RK_MRSZ_PHASE_HC_SHD                ((RK_MRSZ_BASE + 0x0000004C))
#define RK_MRSZ_PHASE_VY_SHD                ((RK_MRSZ_BASE + 0x00000050))
#define RK_MRSZ_PHASE_VC_SHD                ((RK_MRSZ_BASE + 0x00000054))

#define RK_SRSZ_BASE                        (0x40171000U)
#define RK_SRSZ_CTRL                        ((RK_SRSZ_BASE + 0x00000000))
#define RK_SRSZ_SCALE_HY                    ((RK_SRSZ_BASE + 0x00000004))
#define RK_SRSZ_SCALE_HCB                   ((RK_SRSZ_BASE + 0x00000008))
#define RK_SRSZ_SCALE_HCR                   ((RK_SRSZ_BASE + 0x0000000C))
#define RK_SRSZ_SCALE_VY                    ((RK_SRSZ_BASE + 0x00000010))
#define RK_SRSZ_SCALE_VC                    ((RK_SRSZ_BASE + 0x00000014))
#define RK_SRSZ_PHASE_HY                    ((RK_SRSZ_BASE + 0x00000018))
#define RK_SRSZ_PHASE_HC                    ((RK_SRSZ_BASE + 0x0000001C))
#define RK_SRSZ_PHASE_VY                    ((RK_SRSZ_BASE + 0x00000020))
#define RK_SRSZ_PHASE_VC                    ((RK_SRSZ_BASE + 0x00000024))
#define RK_SRSZ_SCALE_LUT_ADDR              ((RK_SRSZ_BASE + 0x00000028))
#define RK_SRSZ_SCALE_LUT                   ((RK_SRSZ_BASE + 0x0000002C))
#define RK_SRSZ_CTRL_SHD                    ((RK_SRSZ_BASE + 0x00000030))
#define RK_SRSZ_SCALE_HY_SHD                ((RK_SRSZ_BASE + 0x00000034))
#define RK_SRSZ_SCALE_HCB_SHD               ((RK_SRSZ_BASE + 0x00000038))
#define RK_SRSZ_SCALE_HCR_SHD               ((RK_SRSZ_BASE + 0x0000003C))
#define RK_SRSZ_SCALE_VY_SHD                ((RK_SRSZ_BASE + 0x00000040))
#define RK_SRSZ_SCALE_VC_SHD                ((RK_SRSZ_BASE + 0x00000044))
#define RK_SRSZ_PHASE_HY_SHD                ((RK_SRSZ_BASE + 0x00000048))
#define RK_SRSZ_PHASE_HC_SHD                ((RK_SRSZ_BASE + 0x0000004C))
#define RK_SRSZ_PHASE_VY_SHD                ((RK_SRSZ_BASE + 0x00000050))
#define RK_SRSZ_PHASE_VC_SHD                ((RK_SRSZ_BASE + 0x00000054))

#define RK_MI_BASE                          (0x40171400U)
#define RK_MI_CTRL                          ((RK_MI_BASE + 0x00000000))
#define RK_MI_INIT                          ((RK_MI_BASE + 0x00000004))
#define RK_MI_MP_Y_BASE_AD_INIT             ((RK_MI_BASE + 0x00000008))
#define RK_MI_MP_Y_SIZE_INIT                ((RK_MI_BASE + 0x0000000C))
#define RK_MI_MP_Y_OFFS_CNT_INIT            ((RK_MI_BASE + 0x00000010))
#define RK_MI_MP_Y_OFFS_CNT_START           ((RK_MI_BASE + 0x00000014))
#define RK_MI_MP_Y_IRQ_OFFS_INIT            ((RK_MI_BASE + 0x00000018))
#define RK_MI_MP_CB_BASE_AD_INIT            ((RK_MI_BASE + 0x0000001C))
#define RK_MI_MP_CB_SIZE_INIT               ((RK_MI_BASE + 0x00000020))
#define RK_MI_MP_CB_OFFS_CNT_INIT           ((RK_MI_BASE + 0x00000024))
#define RK_MI_MP_CB_OFFS_CNT_START          ((RK_MI_BASE + 0x00000028))
#define RK_MI_MP_CR_BASE_AD_INIT            ((RK_MI_BASE + 0x0000002C))
#define RK_MI_MP_CR_SIZE_INIT               ((RK_MI_BASE + 0x00000030))
#define RK_MI_MP_CR_OFFS_CNT_INIT           ((RK_MI_BASE + 0x00000034))
#define RK_MI_MP_CR_OFFS_CNT_START          ((RK_MI_BASE + 0x00000038))
#define RK_MI_SP_Y_BASE_AD_INIT             ((RK_MI_BASE + 0x0000003C))
#define RK_MI_SP_Y_SIZE_INIT                ((RK_MI_BASE + 0x00000040))
#define RK_MI_SP_Y_OFFS_CNT_INIT            ((RK_MI_BASE + 0x00000044))
#define RK_MI_SP_Y_OFFS_CNT_START           ((RK_MI_BASE + 0x00000048))
#define RK_MI_SP_Y_LLENGTH                  ((RK_MI_BASE + 0x0000004C))
#define RK_MI_SP_CB_BASE_AD_INIT            ((RK_MI_BASE + 0x00000050))
#define RK_MI_SP_CB_SIZE_INIT               ((RK_MI_BASE + 0x00000054))
#define RK_MI_SP_CB_OFFS_CNT_INIT           ((RK_MI_BASE + 0x00000058))
#define RK_MI_SP_CB_OFFS_CNT_START          ((RK_MI_BASE + 0x0000005C))
#define RK_MI_SP_CR_BASE_AD_INIT            ((RK_MI_BASE + 0x00000060))
#define RK_MI_SP_CR_SIZE_INIT               ((RK_MI_BASE + 0x00000064))
#define RK_MI_SP_CR_OFFS_CNT_INIT           ((RK_MI_BASE + 0x00000068))
#define RK_MI_SP_CR_OFFS_CNT_START          ((RK_MI_BASE + 0x0000006C))
#define RK_MI_BYTE_CNT                      ((RK_MI_BASE + 0x00000070))
#define RK_MI_CTRL_SHD                      ((RK_MI_BASE + 0x00000074))
#define RK_MI_MP_Y_BASE_AD_SHD              ((RK_MI_BASE + 0x00000078))
#define RK_MI_MP_Y_SIZE_SHD                 ((RK_MI_BASE + 0x0000007C))
#define RK_MI_MP_Y_OFFS_CNT_SHD             ((RK_MI_BASE + 0x00000080))
#define RK_MI_MP_Y_IRQ_OFFS_SHD             ((RK_MI_BASE + 0x00000084))
#define RK_MI_MP_CB_BASE_AD_SHD             ((RK_MI_BASE + 0x00000088))
#define RK_MI_MP_CB_SIZE_SHD                ((RK_MI_BASE + 0x0000008C))
#define RK_MI_MP_CB_OFFS_CNT_SHD            ((RK_MI_BASE + 0x00000090))
#define RK_MI_MP_CR_BASE_AD_SHD             ((RK_MI_BASE + 0x00000094))
#define RK_MI_MP_CR_SIZE_SHD                ((RK_MI_BASE + 0x00000098))
#define RK_MI_MP_CR_OFFS_CNT_SHD            ((RK_MI_BASE + 0x0000009C))
#define RK_MI_SP_Y_BASE_AD_SHD              ((RK_MI_BASE + 0x000000A0))
#define RK_MI_SP_Y_SIZE_SHD                 ((RK_MI_BASE + 0x000000A4))
#define RK_MI_SP_Y_OFFS_CNT_SHD             ((RK_MI_BASE + 0x000000A8))
#define RK_MI_SP_CB_BASE_AD_SHD             ((RK_MI_BASE + 0x000000B0))
#define RK_MI_SP_CB_SIZE_SHD                ((RK_MI_BASE + 0x000000B4))
#define RK_MI_SP_CB_OFFS_CNT_SHD            ((RK_MI_BASE + 0x000000B8))
#define RK_MI_SP_CR_BASE_AD_SHD             ((RK_MI_BASE + 0x000000BC))
#define RK_MI_SP_CR_SIZE_SHD                ((RK_MI_BASE + 0x000000C0))
#define RK_MI_SP_CR_OFFS_CNT_SHD            ((RK_MI_BASE + 0x000000C4))
#define RK_MI_DMA_Y_PIC_START_AD            ((RK_MI_BASE + 0x000000C8))
#define RK_MI_DMA_Y_PIC_WIDTH               ((RK_MI_BASE + 0x000000CC))
#define RK_MI_DMA_Y_LLENGTH                 ((RK_MI_BASE + 0x000000D0))
#define RK_MI_DMA_Y_PIC_SIZE                ((RK_MI_BASE + 0x000000D4))
#define RK_MI_DMA_CB_PIC_START_AD           ((RK_MI_BASE + 0x000000D8))
#define RK_MI_DMA_CR_PIC_START_AD           ((RK_MI_BASE + 0x000000E8))
#define RK_MI_IMSC                          ((RK_MI_BASE + 0x000000F8))
#define RK_MI_RIS                           ((RK_MI_BASE + 0x000000FC))
#define RK_MI_MIS                           ((RK_MI_BASE + 0x00000100))
#define RK_MI_ICR                           ((RK_MI_BASE + 0x00000104))
#define RK_MI_ISR                           ((RK_MI_BASE + 0x00000108))
#define RK_MI_STATUS                        ((RK_MI_BASE + 0x0000010C))
#define RK_MI_STATUS_CLR                    ((RK_MI_BASE + 0x00000110))
#define RK_MI_SP_Y_PIC_WIDTH                ((RK_MI_BASE + 0x00000114))
#define RK_MI_SP_Y_PIC_HEIGHT               ((RK_MI_BASE + 0x00000118))
#define RK_MI_SP_Y_PIC_SIZE                 ((RK_MI_BASE + 0x0000011C))
#define RK_MI_DMA_CTRL                      ((RK_MI_BASE + 0x00000120))
#define RK_MI_DMA_START                     ((RK_MI_BASE + 0x00000124))
#define RK_MI_DMA_STATUS                    ((RK_MI_BASE + 0x00000128))
#define RK_MI_PIXEL_COUNT                   ((RK_MI_BASE + 0x0000012C))
#define RK_MI_MP_Y_BASE_AD_INIT2            ((RK_MI_BASE + 0x00000130))
#define RK_MI_MP_CB_BASE_AD_INIT2           ((RK_MI_BASE + 0x00000134))
#define RK_MI_MP_CR_BASE_AD_INIT2           ((RK_MI_BASE + 0x00000138))
#define RK_MI_SP_Y_BASE_AD_INIT2            ((RK_MI_BASE + 0x0000013C))
#define RK_MI_SP_CB_BASE_AD_INIT2           ((RK_MI_BASE + 0x00000140))
#define RK_MI_SP_CR_BASE_AD_INIT2           ((RK_MI_BASE + 0x00000144))
#define RK_MI_XTD_FORMAT_CTRL               ((RK_MI_BASE + 0x00000148))

#define RK_MIPI_BASE                        (0x40171C00U)
#define RK_MIPI_CTRL                        ((RK_MIPI_BASE + 0x00000000))
#define RK_MIPI_STATUS                      ((RK_MIPI_BASE + 0x00000004))
#define RK_MIPI_IMSC                        ((RK_MIPI_BASE + 0x00000008))
#define RK_MIPI_RIS                         ((RK_MIPI_BASE + 0x0000000C))
#define RK_MIPI_MIS                         ((RK_MIPI_BASE + 0x00000010))
#define RK_MIPI_ICR                         ((RK_MIPI_BASE + 0x00000014))
#define RK_MIPI_ISR                         ((RK_MIPI_BASE + 0x00000018))
#define RK_MIPI_CUR_DATA_ID                 ((RK_MIPI_BASE + 0x0000001C))
#define RK_MIPI_IMG_DATA_SEL                ((RK_MIPI_BASE + 0x00000020))
#define RK_MIPI_ADD_DATA_SEL_1              ((RK_MIPI_BASE + 0x00000024))
#define RK_MIPI_ADD_DATA_SEL_2              ((RK_MIPI_BASE + 0x00000028))
#define RK_MIPI_ADD_DATA_SEL_3              ((RK_MIPI_BASE + 0x0000002C))
#define RK_MIPI_ADD_DATA_SEL_4              ((RK_MIPI_BASE + 0x00000030))
#define RK_MIPI_ADD_DATA_FIFO               ((RK_MIPI_BASE + 0x00000034))
#define RK_MIPI_FIFO_FILL_LEVEL             ((RK_MIPI_BASE + 0x00000038))
#define RK_MIPI_COMPRESSED_MODE             ((RK_MIPI_BASE + 0x0000003C))
#define RK_MIPI_FRAME                       ((RK_MIPI_BASE + 0x00000040))
#define RK_MIPI_GEN_SHORT_DT                ((RK_MIPI_BASE + 0x00000044))
#define RK_MIPI_GEN_SHORT_8_9               ((RK_MIPI_BASE + 0x00000048))
#define RK_MIPI_GEN_SHORT_A_B               ((RK_MIPI_BASE + 0x0000004C))
#define RK_MIPI_GEN_SHORT_C_D               ((RK_MIPI_BASE + 0x00000050))
#define RK_MIPI_GEN_SHORT_E_F               ((RK_MIPI_BASE + 0x00000054))

#define RK_ISP_AFM_BASE                     (0x40172000U)
#define RK_ISP_AFM_CTRL                     ((RK_ISP_AFM_BASE + 0x00000000))
#define RK_ISP_AFM_LT_A                     ((RK_ISP_AFM_BASE + 0x00000004))
#define RK_ISP_AFM_RB_A                     ((RK_ISP_AFM_BASE + 0x00000008))
#define RK_ISP_AFM_LT_B                     ((RK_ISP_AFM_BASE + 0x0000000C))
#define RK_ISP_AFM_RB_B                     ((RK_ISP_AFM_BASE + 0x00000010))
#define RK_ISP_AFM_LT_C                     ((RK_ISP_AFM_BASE + 0x00000014))
#define RK_ISP_AFM_RB_C                     ((RK_ISP_AFM_BASE + 0x00000018))
#define RK_ISP_AFM_THRES                    ((RK_ISP_AFM_BASE + 0x0000001C))
#define RK_ISP_AFM_VAR_SHIFT                ((RK_ISP_AFM_BASE + 0x00000020))
#define RK_ISP_AFM_SUM_A                    ((RK_ISP_AFM_BASE + 0x00000024))
#define RK_ISP_AFM_SUM_B                    ((RK_ISP_AFM_BASE + 0x00000028))
#define RK_ISP_AFM_SUM_C                    ((RK_ISP_AFM_BASE + 0x0000002C))
#define RK_ISP_AFM_LUM_A                    ((RK_ISP_AFM_BASE + 0x00000030))
#define RK_ISP_AFM_LUM_B                    ((RK_ISP_AFM_BASE + 0x00000034))
#define RK_ISP_AFM_LUM_C                    ((RK_ISP_AFM_BASE + 0x00000038))

#define RK_ISP_LSC_BASE                     (0x40172200U)
#define RK_ISP_LSC_CTRL                     ((RK_ISP_LSC_BASE + 0x00000000))
#define RK_ISP_LSC_R_TABLE_ADDR             ((RK_ISP_LSC_BASE + 0x00000004))
#define RK_ISP_LSC_GR_TABLE_ADDR            ((RK_ISP_LSC_BASE + 0x00000008))
#define RK_ISP_LSC_B_TABLE_ADDR             ((RK_ISP_LSC_BASE + 0x0000000C))
#define RK_ISP_LSC_GB_TABLE_ADDR            ((RK_ISP_LSC_BASE + 0x00000010))
#define RK_ISP_LSC_R_TABLE_DATA             ((RK_ISP_LSC_BASE + 0x00000014))
#define RK_ISP_LSC_GR_TABLE_DATA            ((RK_ISP_LSC_BASE + 0x00000018))
#define RK_ISP_LSC_B_TABLE_DATA             ((RK_ISP_LSC_BASE + 0x0000001C))
#define RK_ISP_LSC_GB_TABLE_DATA            ((RK_ISP_LSC_BASE + 0x00000020))
#define RK_ISP_LSC_XGRAD_01                 ((RK_ISP_LSC_BASE + 0x00000024))
#define RK_ISP_LSC_XGRAD_23                 ((RK_ISP_LSC_BASE + 0x00000028))
#define RK_ISP_LSC_XGRAD_45                 ((RK_ISP_LSC_BASE + 0x0000002C))
#define RK_ISP_LSC_XGRAD_67                 ((RK_ISP_LSC_BASE + 0x00000030))
#define RK_ISP_LSC_YGRAD_01                 ((RK_ISP_LSC_BASE + 0x00000034))
#define RK_ISP_LSC_YGRAD_23                 ((RK_ISP_LSC_BASE + 0x00000038))
#define RK_ISP_LSC_YGRAD_45                 ((RK_ISP_LSC_BASE + 0x0000003C))
#define RK_ISP_LSC_YGRAD_67                 ((RK_ISP_LSC_BASE + 0x00000040))
#define RK_ISP_LSC_XSIZE_01                 ((RK_ISP_LSC_BASE + 0x00000044))
#define RK_ISP_LSC_XSIZE_23                 ((RK_ISP_LSC_BASE + 0x00000048))
#define RK_ISP_LSC_XSIZE_45                 ((RK_ISP_LSC_BASE + 0x0000004C))
#define RK_ISP_LSC_XSIZE_67                 ((RK_ISP_LSC_BASE + 0x00000050))
#define RK_ISP_LSC_YSIZE_01                 ((RK_ISP_LSC_BASE + 0x00000054))
#define RK_ISP_LSC_YSIZE_23                 ((RK_ISP_LSC_BASE + 0x00000058))
#define RK_ISP_LSC_YSIZE_45                 ((RK_ISP_LSC_BASE + 0x0000005C))
#define RK_ISP_LSC_YSIZE_67                 ((RK_ISP_LSC_BASE + 0x00000060))
#define RK_ISP_LSC_TABLE_SEL                ((RK_ISP_LSC_BASE + 0x00000064))
#define RK_ISP_LSC_STATUS                   ((RK_ISP_LSC_BASE + 0x00000068))

#define RK_ISP_IS_BASE                      (0x40172300U)
#define RK_ISP_IS_CTRL                      ((RK_ISP_IS_BASE + 0x00000000))
#define RK_ISP_IS_RECENTER                  ((RK_ISP_IS_BASE + 0x00000004))
#define RK_ISP_IS_H_OFFS                    ((RK_ISP_IS_BASE + 0x00000008))
#define RK_ISP_IS_V_OFFS                    ((RK_ISP_IS_BASE + 0x0000000C))
#define RK_ISP_IS_H_SIZE                    ((RK_ISP_IS_BASE + 0x00000010))
#define RK_ISP_IS_V_SIZE                    ((RK_ISP_IS_BASE + 0x00000014))
#define RK_ISP_IS_MAX_DX                    ((RK_ISP_IS_BASE + 0x00000018))
#define RK_ISP_IS_MAX_DY                    ((RK_ISP_IS_BASE + 0x0000001C))
#define RK_ISP_IS_DISPLACE                  ((RK_ISP_IS_BASE + 0x00000020))
#define RK_ISP_IS_H_OFFS_SHD                ((RK_ISP_IS_BASE + 0x00000024))
#define RK_ISP_IS_V_OFFS_SHD                ((RK_ISP_IS_BASE + 0x00000028))
#define RK_ISP_IS_H_SIZE_SHD                ((RK_ISP_IS_BASE + 0x0000002C))
#define RK_ISP_IS_V_SIZE_SHD                ((RK_ISP_IS_BASE + 0x00000030))

#define RK_ISP_HIST_BASE                    (0x40172400U)
#define RK_ISP_HIST_PROP                    ((RK_ISP_HIST_BASE + 0x00000000))
#define RK_ISP_HIST_H_OFFS                  ((RK_ISP_HIST_BASE + 0x00000004))
#define RK_ISP_HIST_V_OFFS                  ((RK_ISP_HIST_BASE + 0x00000008))
#define RK_ISP_HIST_H_SIZE                  ((RK_ISP_HIST_BASE + 0x0000000C))
#define RK_ISP_HIST_V_SIZE                  ((RK_ISP_HIST_BASE + 0x00000010))
#define RK_ISP_HIST_BIN_0                   ((RK_ISP_HIST_BASE + 0x00000014))
#define RK_ISP_HIST_BIN_1                   ((RK_ISP_HIST_BASE + 0x00000018))
#define RK_ISP_HIST_BIN_2                   ((RK_ISP_HIST_BASE + 0x0000001C))
#define RK_ISP_HIST_BIN_3                   ((RK_ISP_HIST_BASE + 0x00000020))
#define RK_ISP_HIST_BIN_4                   ((RK_ISP_HIST_BASE + 0x00000024))
#define RK_ISP_HIST_BIN_5                   ((RK_ISP_HIST_BASE + 0x00000028))
#define RK_ISP_HIST_BIN_6                   ((RK_ISP_HIST_BASE + 0x0000002C))
#define RK_ISP_HIST_BIN_7                   ((RK_ISP_HIST_BASE + 0x00000030))
#define RK_ISP_HIST_BIN_8                   ((RK_ISP_HIST_BASE + 0x00000034))
#define RK_ISP_HIST_BIN_9                   ((RK_ISP_HIST_BASE + 0x00000038))
#define RK_ISP_HIST_BIN_10                  ((RK_ISP_HIST_BASE + 0x0000003C))
#define RK_ISP_HIST_BIN_11                  ((RK_ISP_HIST_BASE + 0x00000040))
#define RK_ISP_HIST_BIN_12                  ((RK_ISP_HIST_BASE + 0x00000044))
#define RK_ISP_HIST_BIN_13                  ((RK_ISP_HIST_BASE + 0x00000048))
#define RK_ISP_HIST_BIN_14                  ((RK_ISP_HIST_BASE + 0x0000004C))
#define RK_ISP_HIST_BIN_15                  ((RK_ISP_HIST_BASE + 0x00000050))
#define RK_ISP_HIST_WEIGHT_00TO30           ((RK_ISP_HIST_BASE + 0x00000054))
#define RK_ISP_HIST_WEIGHT_40TO21           ((RK_ISP_HIST_BASE + 0x00000058))
#define RK_ISP_HIST_WEIGHT_31TO12           ((RK_ISP_HIST_BASE + 0x0000005C))
#define RK_ISP_HIST_WEIGHT_22TO03           ((RK_ISP_HIST_BASE + 0x00000060))
#define RK_ISP_HIST_WEIGHT_13TO43           ((RK_ISP_HIST_BASE + 0x00000064))
#define RK_ISP_HIST_WEIGHT_04TO34           ((RK_ISP_HIST_BASE + 0x00000068))
#define RK_ISP_HIST_WEIGHT_44               ((RK_ISP_HIST_BASE + 0x0000006C))

#define RK_ISP_FILT_BASE                    (0x40172500U)
#define RK_ISP_FILT_MODE                    ((RK_ISP_FILT_BASE + 0x00000000))
#define RK_ISP_FILT_THRESH_BL0              ((RK_ISP_FILT_BASE + 0x00000028))
#define RK_ISP_FILT_THRESH_BL1              ((RK_ISP_FILT_BASE + 0x0000002c))
#define RK_ISP_FILT_THRESH_SH0              ((RK_ISP_FILT_BASE + 0x00000030))
#define RK_ISP_FILT_THRESH_SH1              ((RK_ISP_FILT_BASE + 0x00000034))
#define RK_ISP_FILT_LUM_WEIGHT              ((RK_ISP_FILT_BASE + 0x00000038))
#define RK_ISP_FILT_FAC_SH1                 ((RK_ISP_FILT_BASE + 0x0000003c))
#define RK_ISP_FILT_FAC_SH0                 ((RK_ISP_FILT_BASE + 0x00000040))
#define RK_ISP_FILT_FAC_MID                 ((RK_ISP_FILT_BASE + 0x00000044))
#define RK_ISP_FILT_FAC_BL0                 ((RK_ISP_FILT_BASE + 0x00000048))
#define RK_ISP_FILT_FAC_BL1                 ((RK_ISP_FILT_BASE + 0x0000004C))

#define RK_ISP_CAC_BASE                     (0x40172580U)
#define RK_ISP_CAC_CTRL                     (RK_ISP_CAC_BASE + 0x00000000)
#define RK_ISP_CAC_COUNT_START              (RK_ISP_CAC_BASE + 0x00000004)
#define RK_ISP_CAC_A                        (RK_ISP_CAC_BASE + 0x00000008)
#define RK_ISP_CAC_B                        (RK_ISP_CAC_BASE + 0x0000000C)
#define RK_ISP_CAC_C                        (RK_ISP_CAC_BASE + 0x00000010)
#define RK_ISP_X_NORM                       (RK_ISP_CAC_BASE + 0x00000014)
#define RK_ISP_Y_NORM                       (RK_ISP_CAC_BASE + 0x00000018)

#define RK_ISP_EXP_BASE                     (0x40172600U)
#define RK_ISP_EXP_CTRL                     ((RK_ISP_EXP_BASE + 0x00000000))
#define RK_ISP_EXP_H_OFFSET                 ((RK_ISP_EXP_BASE + 0x00000004))
#define RK_ISP_EXP_V_OFFSET                 ((RK_ISP_EXP_BASE + 0x00000008))
#define RK_ISP_EXP_H_SIZE                   ((RK_ISP_EXP_BASE + 0x0000000C))
#define RK_ISP_EXP_V_SIZE                   ((RK_ISP_EXP_BASE + 0x00000010))
#define RK_ISP_EXP_MEAN_00                  ((RK_ISP_EXP_BASE + 0x00000014))
#define RK_ISP_EXP_MEAN_10                  ((RK_ISP_EXP_BASE + 0x00000018))
#define RK_ISP_EXP_MEAN_20                  ((RK_ISP_EXP_BASE + 0x0000001c))
#define RK_ISP_EXP_MEAN_30                  ((RK_ISP_EXP_BASE + 0x00000020))
#define RK_ISP_EXP_MEAN_40                  ((RK_ISP_EXP_BASE + 0x00000024))
#define RK_ISP_EXP_MEAN_01                  ((RK_ISP_EXP_BASE + 0x00000028))
#define RK_ISP_EXP_MEAN_11                  ((RK_ISP_EXP_BASE + 0x0000002c))
#define RK_ISP_EXP_MEAN_21                  ((RK_ISP_EXP_BASE + 0x00000030))
#define RK_ISP_EXP_MEAN_31                  ((RK_ISP_EXP_BASE + 0x00000034))
#define RK_ISP_EXP_MEAN_41                  ((RK_ISP_EXP_BASE + 0x00000038))
#define RK_ISP_EXP_MEAN_02                  ((RK_ISP_EXP_BASE + 0x0000003c))
#define RK_ISP_EXP_MEAN_12                  ((RK_ISP_EXP_BASE + 0x00000040))
#define RK_ISP_EXP_MEAN_22                  ((RK_ISP_EXP_BASE + 0x00000044))
#define RK_ISP_EXP_MEAN_32                  ((RK_ISP_EXP_BASE + 0x00000048))
#define RK_ISP_EXP_MEAN_42                  ((RK_ISP_EXP_BASE + 0x0000004c))
#define RK_ISP_EXP_MEAN_03                  ((RK_ISP_EXP_BASE + 0x00000050))
#define RK_ISP_EXP_MEAN_13                  ((RK_ISP_EXP_BASE + 0x00000054))
#define RK_ISP_EXP_MEAN_23                  ((RK_ISP_EXP_BASE + 0x00000058))
#define RK_ISP_EXP_MEAN_33                  ((RK_ISP_EXP_BASE + 0x0000005c))
#define RK_ISP_EXP_MEAN_43                  ((RK_ISP_EXP_BASE + 0x00000060))
#define RK_ISP_EXP_MEAN_04                  ((RK_ISP_EXP_BASE + 0x00000064))
#define RK_ISP_EXP_MEAN_14                  ((RK_ISP_EXP_BASE + 0x00000068))
#define RK_ISP_EXP_MEAN_24                  ((RK_ISP_EXP_BASE + 0x0000006c))
#define RK_ISP_EXP_MEAN_34                  ((RK_ISP_EXP_BASE + 0x00000070))
#define RK_ISP_EXP_MEAN_44                  ((RK_ISP_EXP_BASE + 0x00000074))

#define RK_ISP_BLS_BASE                     (0x40172700U)
#define RK_ISP_BLS_CTRL                     ((RK_ISP_BLS_BASE + 0x00000000))
#define RK_ISP_BLS_SAMPLES                  ((RK_ISP_BLS_BASE + 0x00000004))
#define RK_ISP_BLS_H1_START                 ((RK_ISP_BLS_BASE + 0x00000008))
#define RK_ISP_BLS_H1_STOP                  ((RK_ISP_BLS_BASE + 0x0000000c))
#define RK_ISP_BLS_V1_START                 ((RK_ISP_BLS_BASE + 0x00000010))
#define RK_ISP_BLS_V1_STOP                  ((RK_ISP_BLS_BASE + 0x00000014))
#define RK_ISP_BLS_H2_START                 ((RK_ISP_BLS_BASE + 0x00000018))
#define RK_ISP_BLS_H2_STOP                  ((RK_ISP_BLS_BASE + 0x0000001c))
#define RK_ISP_BLS_V2_START                 ((RK_ISP_BLS_BASE + 0x00000020))
#define RK_ISP_BLS_V2_STOP                  ((RK_ISP_BLS_BASE + 0x00000024))
#define RK_ISP_BLS_A_FIXED                  ((RK_ISP_BLS_BASE + 0x00000028))
#define RK_ISP_BLS_B_FIXED                  ((RK_ISP_BLS_BASE + 0x0000002c))
#define RK_ISP_BLS_C_FIXED                  ((RK_ISP_BLS_BASE + 0x00000030))
#define RK_ISP_BLS_D_FIXED                  ((RK_ISP_BLS_BASE + 0x00000034))
#define RK_ISP_BLS_A_MEASURED               ((RK_ISP_BLS_BASE + 0x00000038))
#define RK_ISP_BLS_B_MEASURED               ((RK_ISP_BLS_BASE + 0x0000003c))
#define RK_ISP_BLS_C_MEASURED               ((RK_ISP_BLS_BASE + 0x00000040))
#define RK_ISP_BLS_D_MEASURED               ((RK_ISP_BLS_BASE + 0x00000044))

#define RK_ISP_DPF_BASE                     (0x40172800U)
#define RK_ISP_DPF_MODE                     (RK_ISP_DPF_BASE + 0x00000000)
#define RK_ISP_DPF_STRENGTH_R               (RK_ISP_DPF_BASE + 0x00000004)
#define RK_ISP_DPF_STRENGTH_G               (RK_ISP_DPF_BASE + 0x00000008)
#define RK_ISP_DPF_STRENGTH_B               (RK_ISP_DPF_BASE + 0x0000000C)
#define RK_ISP_DPF_S_WEIGHT_G_1_4           (RK_ISP_DPF_BASE + 0x00000010)
#define RK_ISP_DPF_S_WEIGHT_G_5_6           (RK_ISP_DPF_BASE + 0x00000014)
#define RK_ISP_DPF_S_WEIGHT_RB_1_4          (RK_ISP_DPF_BASE + 0x00000018)
#define RK_ISP_DPF_S_WEIGHT_RB_5_6          (RK_ISP_DPF_BASE + 0x0000001C)
#define RK_ISP_DPF_NULL_COEFF_0             (RK_ISP_DPF_BASE + 0x00000020)
#define RK_ISP_DPF_NULL_COEFF_1             (RK_ISP_DPF_BASE + 0x00000024)
#define RK_ISP_DPF_NULL_COEFF_2             (RK_ISP_DPF_BASE + 0x00000028)
#define RK_ISP_DPF_NULL_COEFF_3             (RK_ISP_DPF_BASE + 0x0000002C)
#define RK_ISP_DPF_NULL_COEFF_4             (RK_ISP_DPF_BASE + 0x00000030)
#define RK_ISP_DPF_NULL_COEFF_5             (RK_ISP_DPF_BASE + 0x00000034)
#define RK_ISP_DPF_NULL_COEFF_6             (RK_ISP_DPF_BASE + 0x00000038)
#define RK_ISP_DPF_NULL_COEFF_7             (RK_ISP_DPF_BASE + 0x0000003C)
#define RK_ISP_DPF_NULL_COEFF_8             (RK_ISP_DPF_BASE + 0x00000040)
#define RK_ISP_DPF_NULL_COEFF_9             (RK_ISP_DPF_BASE + 0x00000044)
#define RK_ISP_DPF_NULL_COEFF_10            (RK_ISP_DPF_BASE + 0x00000048)
#define RK_ISP_DPF_NULL_COEFF_11            (RK_ISP_DPF_BASE + 0x0000004C)
#define RK_ISP_DPF_NULL_COEFF_12            (RK_ISP_DPF_BASE + 0x00000050)
#define RK_ISP_DPF_NULL_COEFF_13            (RK_ISP_DPF_BASE + 0x00000054)
#define RK_ISP_DPF_NULL_COEFF_14            (RK_ISP_DPF_BASE + 0x00000058)
#define RK_ISP_DPF_NULL_COEFF_15            (RK_ISP_DPF_BASE + 0x0000005C)
#define RK_ISP_DPF_NULL_COEFF_16            (RK_ISP_DPF_BASE + 0x00000060)
#define RK_ISP_DPF_NF_GAIN_R                (RK_ISP_DPF_BASE + 0x00000064)
#define RK_ISP_DPF_NF_GAIN_GR               (RK_ISP_DPF_BASE + 0x00000068)
#define RK_ISP_DPF_NF_GAIN_GB               (RK_ISP_DPF_BASE + 0x0000006C)
#define RK_ISP_DPF_NF_GAIN_B                (RK_ISP_DPF_BASE + 0x00000070)

#define RK_ISP_DPCC_BASE                    (0x40172900U)
#define RK_ISP_DPCC_MODE                    (RK_ISP_DPCC_BASE + 0x00000000)
#define RK_ISP_DPCC_OUTPUT_MODE             (RK_ISP_DPCC_BASE + 0x00000004)
#define RK_ISP_DPCC_SET_USE                 (RK_ISP_DPCC_BASE + 0x00000008)
#define RK_ISP_DPCC_METHODS_SET_1           (RK_ISP_DPCC_BASE + 0x0000000C)
#define RK_ISP_DPCC_METHODS_SET_2           (RK_ISP_DPCC_BASE + 0x00000010)
#define RK_ISP_DPCC_METHODS_SET_3           (RK_ISP_DPCC_BASE + 0x00000014)
#define RK_ISP_DPCC_LINE_THRESH_1           (RK_ISP_DPCC_BASE + 0x00000018)
#define RK_ISP_DPCC_LINE_MAD_FAC_1          (RK_ISP_DPCC_BASE + 0x0000001C)
#define RK_ISP_DPCC_PG_FAC_1                (RK_ISP_DPCC_BASE + 0x00000020)
#define RK_ISP_DPCC_RND_THRESH_1            (RK_ISP_DPCC_BASE + 0x00000024)
#define RK_ISP_DPCC_RG_FAC_1                (RK_ISP_DPCC_BASE + 0x00000028)
#define RK_ISP_DPCC_LINE_THRESH_2           (RK_ISP_DPCC_BASE + 0x0000002C)
#define RK_ISP_DPCC_LINE_MAD_FAC_2          (RK_ISP_DPCC_BASE + 0x00000030)
#define RK_ISP_DPCC_PG_FAC_2                (RK_ISP_DPCC_BASE + 0x00000034)
#define RK_ISP_DPCC_RND_THRESH_2            (RK_ISP_DPCC_BASE + 0x00000038)
#define RK_ISP_DPCC_RG_FAC_2                (RK_ISP_DPCC_BASE + 0x0000003C)
#define RK_ISP_DPCC_LINE_THRESH_3           (RK_ISP_DPCC_BASE + 0x00000040)
#define RK_ISP_DPCC_LINE_MAD_FAC_3          (RK_ISP_DPCC_BASE + 0x00000044)
#define RK_ISP_DPCC_PG_FAC_3                (RK_ISP_DPCC_BASE + 0x00000048)
#define RK_ISP_DPCC_RND_THRESH_3            (RK_ISP_DPCC_BASE + 0x0000004C)
#define RK_ISP_DPCC_RG_FAC_3                (RK_ISP_DPCC_BASE + 0x00000050)
#define RK_ISP_DPCC_RO_LIMITS               (RK_ISP_DPCC_BASE + 0x00000054)
#define RK_ISP_DPCC_RND_OFFS                (RK_ISP_DPCC_BASE + 0x00000058)
#define RK_ISP_DPCC_BPT_CTRL                (RK_ISP_DPCC_BASE + 0x0000005C)
#define RK_ISP_DPCC_BPT_NUMBER              (RK_ISP_DPCC_BASE + 0x00000060)
#define RK_ISP_DPCC_BPT_ADDR                (RK_ISP_DPCC_BASE + 0x00000064)
#define RK_ISP_DPCC_BPT_DATA                (RK_ISP_DPCC_BASE + 0x00000068)

#define RK_ISP_WDR_BASE                     (0x40172A00U)
#define RK_ISP_WDR_CTRL                     (RK_ISP_WDR_BASE + 0x00000000)
#define RK_ISP_WDR_TONECURVE_1              (RK_ISP_WDR_BASE + 0x00000004)
#define RK_ISP_WDR_TONECURVE_2              (RK_ISP_WDR_BASE + 0x00000008)
#define RK_ISP_WDR_TONECURVE_3              (RK_ISP_WDR_BASE + 0x0000000C)
#define RK_ISP_WDR_TONECURVE_4              (RK_ISP_WDR_BASE + 0x00000010)
#define RK_ISP_WDR_TONECURVE_YM_0           (RK_ISP_WDR_BASE + 0x00000014)
#define RK_ISP_WDR_TONECURVE_YM_1           (RK_ISP_WDR_BASE + 0x00000018)
#define RK_ISP_WDR_TONECURVE_YM_2           (RK_ISP_WDR_BASE + 0x0000001C)
#define RK_ISP_WDR_TONECURVE_YM_3           (RK_ISP_WDR_BASE + 0x00000020)
#define RK_ISP_WDR_TONECURVE_YM_4           (RK_ISP_WDR_BASE + 0x00000024)
#define RK_ISP_WDR_TONECURVE_YM_5           (RK_ISP_WDR_BASE + 0x00000028)
#define RK_ISP_WDR_TONECURVE_YM_6           (RK_ISP_WDR_BASE + 0x0000002C)
#define RK_ISP_WDR_TONECURVE_YM_7           (RK_ISP_WDR_BASE + 0x00000030)
#define RK_ISP_WDR_TONECURVE_YM_8           (RK_ISP_WDR_BASE + 0x00000034)
#define RK_ISP_WDR_TONECURVE_YM_9           (RK_ISP_WDR_BASE + 0x00000038)
#define RK_ISP_WDR_TONECURVE_YM_10          (RK_ISP_WDR_BASE + 0x0000003C)
#define RK_ISP_WDR_TONECURVE_YM_11          (RK_ISP_WDR_BASE + 0x00000040)
#define RK_ISP_WDR_TONECURVE_YM_12          (RK_ISP_WDR_BASE + 0x00000044)
#define RK_ISP_WDR_TONECURVE_YM_13          (RK_ISP_WDR_BASE + 0x00000048)
#define RK_ISP_WDR_TONECURVE_YM_14          (RK_ISP_WDR_BASE + 0x0000004C)
#define RK_ISP_WDR_TONECURVE_YM_15          (RK_ISP_WDR_BASE + 0x00000050)
#define RK_ISP_WDR_TONECURVE_YM_16          (RK_ISP_WDR_BASE + 0x00000054)
#define RK_ISP_WDR_TONECURVE_YM_17          (RK_ISP_WDR_BASE + 0x00000058)
#define RK_ISP_WDR_TONECURVE_YM_18          (RK_ISP_WDR_BASE + 0x0000005C)
#define RK_ISP_WDR_TONECURVE_YM_19          (RK_ISP_WDR_BASE + 0x00000060)
#define RK_ISP_WDR_TONECURVE_YM_20          (RK_ISP_WDR_BASE + 0x00000064)
#define RK_ISP_WDR_TONECURVE_YM_21          (RK_ISP_WDR_BASE + 0x00000068)
#define RK_ISP_WDR_TONECURVE_YM_22          (RK_ISP_WDR_BASE + 0x0000006C)
#define RK_ISP_WDR_TONECURVE_YM_23          (RK_ISP_WDR_BASE + 0x00000070)
#define RK_ISP_WDR_TONECURVE_YM_24          (RK_ISP_WDR_BASE + 0x00000074)
#define RK_ISP_WDR_TONECURVE_YM_25          (RK_ISP_WDR_BASE + 0x00000078)
#define RK_ISP_WDR_TONECURVE_YM_26          (RK_ISP_WDR_BASE + 0x0000007C)
#define RK_ISP_WDR_TONECURVE_YM_27          (RK_ISP_WDR_BASE + 0x00000080)
#define RK_ISP_WDR_TONECURVE_YM_28          (RK_ISP_WDR_BASE + 0x00000084)
#define RK_ISP_WDR_TONECURVE_YM_29          (RK_ISP_WDR_BASE + 0x00000088)
#define RK_ISP_WDR_TONECURVE_YM_30          (RK_ISP_WDR_BASE + 0x0000008C)
#define RK_ISP_WDR_TONECURVE_YM_31          (RK_ISP_WDR_BASE + 0x00000090)
#define RK_ISP_WDR_TONECURVE_YM_32          (RK_ISP_WDR_BASE + 0x00000094)
#define RK_ISP_WDR_OFFSET                   (RK_ISP_WDR_BASE + 0x00000098)
#define RK_ISP_WDR_DELTAMIN                 (RK_ISP_WDR_BASE + 0x0000009C)
#define RK_ISP_WDR_TONECURVE_1_SHD          (RK_ISP_WDR_BASE + 0x000000A0)
#define RK_ISP_WDR_TONECURVE_2_SHD          (RK_ISP_WDR_BASE + 0x000000A4)
#define RK_ISP_WDR_TONECURVE_3_SHD          (RK_ISP_WDR_BASE + 0x000000A8)
#define RK_ISP_WDR_TONECURVE_4_SHD          (RK_ISP_WDR_BASE + 0x000000AC)
#define RK_ISP_WDR_TONECURVE_YM_0_SHD       (RK_ISP_WDR_BASE + 0x000000B0)
#define RK_ISP_WDR_TONECURVE_YM_1_SHD       (RK_ISP_WDR_BASE + 0x000000B4)
#define RK_ISP_WDR_TONECURVE_YM_2_SHD       (RK_ISP_WDR_BASE + 0x000000B8)
#define RK_ISP_WDR_TONECURVE_YM_3_SHD       (RK_ISP_WDR_BASE + 0x000000BC)
#define RK_ISP_WDR_TONECURVE_YM_4_SHD       (RK_ISP_WDR_BASE + 0x000000C0)
#define RK_ISP_WDR_TONECURVE_YM_5_SHD       (RK_ISP_WDR_BASE + 0x000000C4)
#define RK_ISP_WDR_TONECURVE_YM_6_SHD       (RK_ISP_WDR_BASE + 0x000000C8)
#define RK_ISP_WDR_TONECURVE_YM_7_SHD       (RK_ISP_WDR_BASE + 0x000000CC)
#define RK_ISP_WDR_TONECURVE_YM_8_SHD       (RK_ISP_WDR_BASE + 0x000000D0)
#define RK_ISP_WDR_TONECURVE_YM_9_SHD       (RK_ISP_WDR_BASE + 0x000000D4)
#define RK_ISP_WDR_TONECURVE_YM_10_SHD      (RK_ISP_WDR_BASE + 0x000000D8)
#define RK_ISP_WDR_TONECURVE_YM_11_SHD      (RK_ISP_WDR_BASE + 0x000000DC)
#define RK_ISP_WDR_TONECURVE_YM_12_SHD      (RK_ISP_WDR_BASE + 0x000000E0)
#define RK_ISP_WDR_TONECURVE_YM_13_SHD      (RK_ISP_WDR_BASE + 0x000000E4)
#define RK_ISP_WDR_TONECURVE_YM_14_SHD      (RK_ISP_WDR_BASE + 0x000000E8)
#define RK_ISP_WDR_TONECURVE_YM_15_SHD      (RK_ISP_WDR_BASE + 0x000000EC)
#define RK_ISP_WDR_TONECURVE_YM_16_SHD      (RK_ISP_WDR_BASE + 0x000000F0)
#define RK_ISP_WDR_TONECURVE_YM_17_SHD      (RK_ISP_WDR_BASE + 0x000000F4)
#define RK_ISP_WDR_TONECURVE_YM_18_SHD      (RK_ISP_WDR_BASE + 0x000000F8)
#define RK_ISP_WDR_TONECURVE_YM_19_SHD      (RK_ISP_WDR_BASE + 0x000000FC)
#define RK_ISP_WDR_TONECURVE_YM_20_SHD      (RK_ISP_WDR_BASE + 0x00000100)
#define RK_ISP_WDR_TONECURVE_YM_21_SHD      (RK_ISP_WDR_BASE + 0x00000104)
#define RK_ISP_WDR_TONECURVE_YM_22_SHD      (RK_ISP_WDR_BASE + 0x00000108)
#define RK_ISP_WDR_TONECURVE_YM_23_SHD      (RK_ISP_WDR_BASE + 0x0000010C)
#define RK_ISP_WDR_TONECURVE_YM_24_SHD      (RK_ISP_WDR_BASE + 0x00000110)
#define RK_ISP_WDR_TONECURVE_YM_25_SHD      (RK_ISP_WDR_BASE + 0x00000114)
#define RK_ISP_WDR_TONECURVE_YM_26_SHD      (RK_ISP_WDR_BASE + 0x00000118)
#define RK_ISP_WDR_TONECURVE_YM_27_SHD      (RK_ISP_WDR_BASE + 0x0000011C)
#define RK_ISP_WDR_TONECURVE_YM_28_SHD      (RK_ISP_WDR_BASE + 0x00000120)
#define RK_ISP_WDR_TONECURVE_YM_29_SHD      (RK_ISP_WDR_BASE + 0x00000124)
#define RK_ISP_WDR_TONECURVE_YM_30_SHD      (RK_ISP_WDR_BASE + 0x00000128)
#define RK_ISP_WDR_TONECURVE_YM_31_SHD      (RK_ISP_WDR_BASE + 0x0000012C)
#define RK_ISP_WDR_TONECURVE_YM_32_SHD      (RK_ISP_WDR_BASE + 0x00000130)
#define RK_ISP_WDR_CTRL0                    (RK_ISP_WDR_BASE + 0x00000150)
#define RK_ISP_WDR_CTRL1                    (RK_ISP_WDR_BASE + 0x00000154)
#define RK_ISP_WDR_BLKOFF                   (RK_ISP_WDR_BASE + 0x00000158)
#define RK_ISP_WDR_AVG_CLIP                 (RK_ISP_WDR_BASE + 0x0000015C)
#define RK_ISP_WDR_COE_0                    (RK_ISP_WDR_BASE + 0x00000160)
#define RK_ISP_WDR_COE_1                    (RK_ISP_WDR_BASE + 0x00000164)
#define RK_ISP_WDR_COE_2                    (RK_ISP_WDR_BASE + 0x00000168)
#define RK_ISP_WDR_COE_OFF                  (RK_ISP_WDR_BASE + 0x0000016C)
#endif
#endif