# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2020 Rockchip Electronics Co., Ltd.

PROJECT		:= Swallow
SOC		:= Swallow
CPU		:= -mcpu=cortex-m0 -mthumb

include ../../common/GCC/Cortex-M.mk
